In [1]:
#!pip install yfinance --upgrade --no-cache-dir

In [2]:
#!pip freeze | grep yfinance

In [1]:
from datetime import datetime, timedelta
import sys

import pandas as pd

#from twelvedata import TDClient
#import yfinance as yf

sys.path.append('..')
import yf_clone.yfinance as yfc
#import yfinance as yfc

sent: <object object at 0x1238d47c0>

In [2]:
#with open('./.env', 'r') as f:
#    for line in f:
#        if line.startswith('TWELVE_DATA_API_KEY'):
#            api_key = line.split('=')[-1].strip()
#            
#td_client = TDClient(apikey=api_key)

In [3]:
DATA = '../data'
TODAY = datetime.now().date()
TOMORROW  = TODAY + timedelta(1)
STATE_RANGE = range(3, 11)
START = '1965-01-01'
TOMORROW

datetime.date(2026, 6, 19)

In [4]:
def td2yf(df):
    'Convert twelvedata format to yfinance format'
    df.drop(columns=['volume'], inplace=True)
    df['Value'] = df.close.copy()
    symbols = sorted(list({i[0] for i in df.index}))
    dfs = [df.loc[sym] for sym in symbols]
    for sym, df in zip(symbols, dfs):
        df.columns = pd.MultiIndex.from_tuples(
            [(col, sym) for col in [
                'Open', 'High', 'Low', 'Close', 'Value']])
    return pd.concat(dfs, axis=1).astype(np.float64)

In [5]:
def download_td(symbols, start, end):
    df = td_client.time_series(
        symbol=symbols,
        interval='1day',
        start_date=start,
        end_date=end,
        outputsize=5000,
        timezone='Exchange',
        order='asc'
    ).as_pandas()
    df = td2yf(df)
    return df

In [6]:
#sp = download_td('^GSPC', start=START, end=str(TOMORROW))
#print(sp.shape)
#sp.head()

In [7]:
cols = ['Close', 'High', 'Low', 'Open', 'Volume']
sp = yfc.download(
    '^GSPC', start=START, end=str(TOMORROW)).sort_index()
#).sort_index()
sp.head()

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open   Volume
Ticker          ^GSPC      ^GSPC      ^GSPC      ^GSPC    ^GSPC
Date
1965-01-04  84.230003  85.150002  83.769997  84.750000  3930000
1965-01-05  84.629997  85.019997  84.019997  84.230003  4110000
1965-01-06  84.889999  85.379997  84.449997  84.629997  4850000
1965-01-07  85.260002  85.620003  84.660004  84.889999  5080000
1965-01-08  85.370003  85.839996  84.910004  85.260002  5340000

In [8]:
sp.columns = cols
sp['Adj Close'] = sp.Close

path = '../data'
sp.to_csv(f'{path}/sp1950.csv')

In [12]:
#nyse = yf.download(
#    '^NYA', start=START, end=str(TOMORROW)).sort_index()
#nyse.columns = cols
#nyse['Adj Close'] = nyse.Close

nas = yfc.download(
    '^IXIC', start=START, end=str(TOMORROW)).sort_index()
nas.columns = cols
nas['Adj Close'] = nas.Close

#wil = yf.download(
#    '^W5000', start='1990-01-01', end=str(TOMORROW))

#nyse.to_csv(f'{path}/nya1965.csv')
nas.to_csv(f'{path}/nasdaq1965.csv')
#wil.to_csv(f'{path}/wilshire1990.csv')

#sp = pd.read_csv(f'{DATA}/sp1950.csv')
#nyse = pd.read_csv(f'{DATA}/nya1965.csv')
#nas = pd.read_csv(f'{DATA}/nasdaq1965.csv')

#wil = pd.read_csv(f'{DATA}/wilshire1990.csv')

[*********************100%***********************]  1 of 1 completed

In [10]:
sp.tail()

,Close,High,Low,Open,Volume,Adj Close
Date,,,,,,
2026-06-12,7431.459961,7456.399902,7363.009766,7410.850098,4950530000,7431.459961
2026-06-15,7554.290039,7577.919922,7516.750000,7516.750000,5674670000,7554.290039
2026-06-16,7511.350098,7564.959961,7508.680176,7548.779785,5286210000,7511.350098
2026-06-17,7420.100098,7532.169922,7402.609863,7524.500000,5883740000,7420.100098
2026-06-18,7500.580078,7511.069824,7468.319824,7487.359863,6250457000,7500.580078

In [11]:
nas.tail()

,Close,High,Low,Open,Volume,Adj Close
Date,,,,,,
2026-06-12,25888.839844,26010.310547,25599.939453,25783.359375,10337400000,25888.839844
2026-06-15,26683.939453,26687.560547,26438.769531,26447.230469,10590270000,26683.939453
2026-06-16,26376.339844,26788.619141,26369.390625,26649.970703,11132830000,26376.339844
2026-06-17,26021.660156,26511.550781,25960.410156,26493.820312,11443600000,26021.660156
2026-06-18,26517.931641,26559.742188,26188.687500,26410.623047,17335631000,26517.931641

In [34]:
#sp.loc[pd.to_datetime('2026-06-15'), 'Close'] = 7554.290039

In [12]:
break

SyntaxError: 'break' outside loop (668683560.py, line 1)

In [ ]:
import json

with open('/Users/damiansp/Desktop/indices.json', 'r') as f:
    stocks = json.load(f)

In [ ]:
stocks['data']

In [ ]:
[d for d in stocks['data'] if d['country'] == 'United States'
]#and 'S&P' in d['name']                
 #and d['exchange'] in ['NSE', 'NASDAQ', 'OTC']]

In [ ]:
# if yahoo finance not working us twelvedata instead
import os

from dotenv import load_dotenv
import matplotlib.pyplot as plt
import pandas as pd
from twelvedata import TDClient
from twelvedata.exceptions import BadRequestError

load_dotenv()

In [ ]:
API_KEY = os.getenv('TWELVE_DATA_API_KEY')

In [ ]:
client = TDClient(apikey=API_KEY)

In [ ]:
dfs = []
start = START
end = str(TOMORROW)

df = client.time_series(
    symbol='GSPC',  # IVV: S&P, NASDAQ
    interval='1day',
    start_date=START,
    end_date=str(TOMORROW),
    outputsize=5000,
    timezone='Exchange',
    order='asc'
).as_pandas()
dfs.append(df)

In [ ]:
end = str(dfs[-1].index[0]).split()[0]
start = datetime.fromisoformat(end) - timedelta(20 * 365)

while str(start) > START:
    print(str(start), end)
    try:
        df = client.time_series(
            symbol='IVV',  # Vanguard 500, Nasdaq Composite
            interval='1day',
            start_date=start,
            end_date=end,
            outputsize=5000,
            timezone='Exchange',
            order='asc'
        ).as_pandas()
        dfs.append(df)
    except BadRequestError:
        break
    end = str(dfs[-1].index[0]).split()[0]
    start = datetime.fromisoformat(end) - timedelta(20 * 365)

In [ ]:
df = pd.concat(dfs)
df.sort_index(inplace=True)

In [ ]:
df.head()

In [ ]:
plt.plot(df.index, df.close);

In [ ]:
end = str(df.index[0]).split()[0]
start = datetime.fromisoformat(end) - timedelta(20 * 365)
start, end

In [ ]:
data = (
    yf
    .download({'AATK', 'ABCO', 'ABAC', 'ABCW', 'AANB', 'AACC', 'ABBC'}, start='2020-01-01', end=TOMORROW)
    .rename(columns={'Adj Close': 'AdjClose'}))#['AdjClose']
data

In [ ]:
x = sp['Adj Close'].to_numpy()
np.append([np.nan], x[1:] / x[:-1])

In [ ]:
def get_daily_changes(series):
    x = series.to_numpy()
    return np.append([1], x[1:] / x[:-1])

In [ ]:
def prep_df(df, name):
    df.index = pd.to_datetime(df.index)
    df[f'{name}_daily'] = get_daily_changes(df['Adj Close'])
    df.rename(columns={'Adj Close': name}, inplace=True)
    return df[[name, f'{name}_daily']]

In [ ]:
[sp, nyse, nas, wil] = [
    prep_df(df, name) 
    for df, name in zip(
        [sp, nyse, nas, wil], ['sp', 'nyse', 'nas', 'wil'])]
sp.head()

In [ ]:
nyse.head()

In [ ]:
nas.head()

In [ ]:
def find_best_mod(
        daily,
        n_states=[6, 7, 8],
        max_iter=1000,
        reps=3,
        best_logprob=None,
        best_mod=None,
        best_states=None):
    daily = np.reshape(daily.values, [-1, 1])
    best_logprob = best_logprob or -np.inf
    best_mod = best_mod or None
    best_states = best_states or None
    for states in n_states:
        for rep in range(reps):
            try:
                print(f'rep {rep + 1}', end='\r')
                for cov in ['spherical', 'diag', 'full']:
                    mod = GaussianHMM(
                        n_components=states,
                        covariance_type=cov,
                        n_iter=max_iter
                    ).fit(daily)
                    logprob = mod.score(daily)
                    if logprob > best_logprob:
                        print(f'New best - States: {states} (cov: {cov})')
                        best_logprob = logprob
                        best_mod = mod
                        best_states = states
            except ValueError:
                pass
    return best_mod, best_logprob, best_states

In [ ]:
def get_preds(daily, mod):
    daily = np.reshape(daily.values, [-1, 1])
    states = mod.predict(daily)
    means = np.squeeze(mod.means_)
    sds = np.squeeze(np.sqrt(mod.covars_))
    preds = np.array([means[state] for state in states])
    ses = np.array([1.96 * sds[state] for state in states])
    return preds, ses, means, states[-1]

In [ ]:
def plot_mod(df, preds, ses, name):
    daily = f'{name}_daily'
    plt.plot(df[daily], label='daily')
    plt.plot(df.index, preds, label='preds')
    plt.legend()

    plt.figure()
    plt.plot(df[daily], label='daily')
    plt.plot(
        df.index, preds, label='preds', color='orange', linewidth=3)
    plt.plot(df.index, preds + ses, color='orange', linestyle='-.')
    plt.plot(df.index, preds - ses, color='orange', linestyle='-.')
    plt.axhline(y=1, color='k')
    plt.ylim([0.95, 1.05]);
    plt.xlim([df.index[-500], df.index[-1]])

    plt.figure()
    plt.plot(df[name])
    plt.xlim([df.index[-500], df.index[-1]])
    sub = df.iloc[-500:, :]
    plt.ylim(
        0.95 * sub[name].min(), 1.05 * sub[name].max());

In [ ]:
def get_expected_val(mod, current_state, means):
    return np.dot(mod.transmat_[current_state, :], means)

In [ ]:
# start search from previous day's best
with open(f'{DATA}/hmm_mods.pkl', 'rb') as f:
    out_data  = pickle.load(f)

out_data

In [ ]:
sp_prob, sp_mod, sp_best_states = (
    out_data['^GSPC']['logprob'], out_data['^GSPC']['mod'], out_data['^GSPC']['n_states'])
nyse_prob, nyse_mod, nyse_best_states = (
    out_data['^NYA']['logprob'], out_data['^NYA']['mod'], out_data['^NYA']['n_states'])
nas_prob, nas_mod, nas_best_states = (
    out_data['^IXIC']['logprob'], out_data['^IXIC']['mod'], out_data['^IXIC']['n_states'])
wil_prob, wil_mod, wil_best_states = (
    out_data['^W5000']['logprob'], out_data['^W5000']['mod'], out_data['^W5000']['n_states'])

In [ ]:
type(sp_mod)

## S&P

In [ ]:
warnings.filterwarnings('ignore', category=RuntimeWarning)

In [ ]:
#sp_prob = None
#sp_mod = None
#sp_best_states = None

In [ ]:
sp_mod, sp_prob, sp_best_states = find_best_mod(
    sp.sp_daily,
    n_states=STATE_RANGE,
    best_logprob=sp_prob,
    best_mod=sp_mod,
    best_states=sp_best_states)
sp_preds, sp_ses, sp_means, sp_current = get_preds(sp.sp_daily, sp_mod)
plot_mod(sp, sp_preds, sp_ses, 'sp')
sp_exp = get_expected_val(sp_mod, sp_current, sp_means)
print(sp_exp)

## NYSE

In [ ]:
#nyse_prob = None
#nyse_mod = None
#nyse_best_states = None

In [ ]:
nyse_mod, nyse_prob, nyse_best_states = find_best_mod(
    nyse.nyse_daily,
    n_states=STATE_RANGE,
    best_logprob=nyse_prob,
    best_mod=nyse_mod,
    best_states=nyse_best_states)
nyse_preds, nyse_ses, nyse_means, nyse_current = get_preds(
    nyse.nyse_daily, nyse_mod)
plot_mod(nyse, nyse_preds, nyse_ses, 'nyse')
nyse_exp = get_expected_val(nyse_mod, nyse_current, nyse_means)
print(nyse_exp)

## Nasdaq

In [ ]:
#nas_prob = None
#nas_mod = None
#nas_best_states = None

In [ ]:
nas_mod, nas_prob, nas_best_states = find_best_mod(
    nas.nas_daily,
    n_states=STATE_RANGE,
    best_logprob=nas_prob,
    best_mod=nas_mod,
    best_states=nas_best_states)
nas_preds, nas_ses, nas_means, nas_current = get_preds(
    nas.nas_daily, nas_mod)
plot_mod(nas, nas_preds, nas_ses, 'nas')
nas_exp = get_expected_val(nas_mod, nas_current, nas_means)
print(nas_exp)

## Wilshire

In [ ]:
#wil_prob = None
#wil_mod = None
#wil_best_states = None

In [ ]:
wil_mod, wil_prob, wil_best_states = find_best_mod(
    wil.wil_daily,
    n_states=STATE_RANGE,
    best_logprob=wil_prob,
    best_mod=wil_mod,
    best_states=wil_best_states)
wil_preds, wil_ses, wil_means, wil_current = get_preds(
    wil.wil_daily, wil_mod)
plot_mod(wil, wil_preds, wil_ses, 'wil')
wil_exp = get_expected_val(wil_mod, wil_current, wil_means)
print(wil_exp)

In [ ]:
#sp_best_states = len(np.unique(sp_preds))
#nyse_best_states = len(np.unique(nyse_preds))
#nas_best_states = len(np.unique(nas_preds))
#wil_best_states = len(np.unique(wil_preds))

In [ ]:
out_data = {
    '^GSPC': {'logprob': sp_prob, 'mod': sp_mod, 'n_states': sp_best_states},
    '^NYA': {'logprob': nyse_prob, 'mod': nyse_mod, 'n_states': nyse_best_states},
    '^IXIC': {'logprob': nas_prob, 'mod': nas_mod, 'n_states': nas_best_states},
    '^W5000': {'logprob': wil_prob, 'mod': wil_mod, 'n_states': wil_best_states}}
with open(f'{DATA}/hmm_mods_indices.pkl', 'wb') as f:
    pickle.dump(out_data, f)

In [ ]:
print(
    sp_best_states, nyse_best_states, nas_best_states, wil_best_states)
mean_states = (
    (sp_best_states
     + nyse_best_states
     + nas_best_states
     + wil_best_states)
    / 4)
mean_states

In [ ]:
N_STATES = int(round(mean_states))
N_STATES

In [ ]:
exp = (sp_exp + nyse_exp + nas_exp + wil_exp) / 4
exp

In [ ]:
for df, name, exp in zip(
        [sp, nyse, nas, wil],
        ['sp', 'nyse', 'nas', 'wil'],
        [sp_preds, nyse_preds, nas_preds, wil_preds]):
    df[f'{name}_exp'] = exp

In [ ]:
df = pd.concat([sp, nyse, nas, wil], axis=1)
df.tail()

In [ ]:
df['mean_exp'] = (
    df[['sp_exp', 'nyse_exp', 'nas_exp', 'wil_exp']].mean(axis=1))

In [ ]:
plt.figure(figsize=[15, 8])
plt.plot(df.sp_exp, label='sp')
plt.plot(df.nyse_exp, label='nyse')
plt.plot(df.nas_exp, label='nasdaq')
plt.plot(df.wil_exp, label='wilshire')

plt.legend();

In [ ]:
plt.figure(figsize=[15, 8])
plt.plot(df.sp_exp, alpha=0.5)
plt.plot(df.nyse_exp, alpha=0.5)
plt.plot(df.nas_exp, alpha=0.5)
plt.plot(df.wil_exp, alpha=0.5)
plt.plot(df.mean_exp, linewidth=3)
plt.axhline(y=1, color='k');

In [ ]:
TODAY = datetime.now()
plt.figure(figsize=[15, 8])
plt.plot(df.sp_exp, alpha=0.5)
plt.plot(df.nyse_exp, alpha=0.5)
plt.plot(df.nas_exp, alpha=0.5)
plt.plot(df.wil_exp, alpha=0.5)
plt.plot(df.mean_exp, linewidth=3)
plt.axhline(y=1, color='k')
plt.xlim(pd.to_datetime('2010-01-01'), TODAY);

In [ ]:
TODAY = datetime.now()
plt.figure(figsize=[15, 8])
plt.plot(df.sp_exp, alpha=0.5)
plt.plot(df.nyse_exp, alpha=0.5)
plt.plot(df.nas_exp, alpha=0.5)
plt.plot(df.wil_exp, alpha=0.5)
plt.plot(df.mean_exp, linewidth=3)
plt.xlim(pd.to_datetime('2020-01-01'), TODAY);
plt.axhline(y = 1, color='k');

In [ ]:
plt.figure(figsize=[15, 8])
plt.plot(df.sp_exp, alpha=0.5)
plt.plot(df.nyse_exp, alpha=0.5)
plt.plot(df.nas_exp, alpha=0.5)
plt.plot(df.wil_exp, alpha=0.5)
plt.plot(df.mean_exp, linewidth=3)
plt.axhline(y=1, color='k')
plt.xlim(pd.to_datetime('2021-01-01'), TODAY)
plt.ylim([0.995, 1.005]);

In [ ]:
df = df[df.index >= pd.to_datetime('1970-01-01')]

In [ ]:
try:
    df['state'] = pd.qcut(
        df.mean_exp,
        N_STATES,
        retbins=False,
        duplicates='drop',
        labels=range(N_STATES))
except ValueError:
    try:
        df['state'] = pd.qcut(
            df.mean_exp,
            N_STATES,
            retbins=False,
            duplicates='drop',
            labels=range(N_STATES - 1))
    except ValueError:
        df['state'] = pd.qcut(
            df.mean_exp,
            N_STATES,
            retbins=False,
            duplicates='drop',
            labels=range(N_STATES - 2))

In [ ]:
df.state.value_counts()

In [ ]:
plt.figure(figsize=[15, 8])
plt.plot(df.state);

In [ ]:
plt.figure(figsize=[15, 8])
plt.plot(df.state)
plt.xlim(pd.to_datetime('2010-01-01'), TODAY);

plt.figure(figsize=[15, 8])
plt.plot(df.state)
plt.xlim(pd.to_datetime('2021-01-01'), TODAY);

plt.figure(figsize=[15, 8])
plt.plot(df.state)
plt.xlim(pd.to_datetime('2022-01-01'), TODAY);

In [ ]:
transitions = Counter()
for i in range(len(df.state) - 1):
    state = df.state[i]
    nxt = df.state[i + 1]
    transitions[(state, nxt)] += 1

In [ ]:
df.to_csv(f'{DATA}/hmm_exp_returns.csv')

In [ ]:
TODAY

In [ ]:
CURRENT_STATE = df.state[-1]
CURRENT_STATE

In [ ]:
possible_transitions = sorted(
    [k for k in transitions.keys() if k[0] == CURRENT_STATE])
state_sum = 0
for pt in possible_transitions:
    n_trans = transitions[pt]
    state_sum += n_trans
    print(f'{pt}: {n_trans}')

print()

data = []
for pt in possible_transitions:
    n_trans = transitions[pt]
    print(f'{pt}: {n_trans / state_sum:.4f}')
    data.append([pt[1], n_trans / state_sum])

In [ ]:
trans_df = pd.DataFrame(data, columns=['next_state', 'prob'])
trans_df

In [ ]:
trans_df.to_csv('../data/transition_probs.csv', index=False)

In [ ]:
df.state.value_counts()

In [ ]:
state_var = (
    df[['state', 'mean_exp']].groupby('state').agg(['mean', 'std']))
state_var.columns = ['mean', 'std']
state_var
state_var['ci'] = state_var.apply(
    lambda row: [
        row['mean'] - 1.96*row['std'],
        row['mean'] + 1.96*row['std']], axis=1)
state_var

In [ ]:
plt.scatter(state_var.index, state_var['mean'])
for state in range(state_var.index.max() + 1):
    plt.plot([state, state], state_var.loc[state, 'ci'], color='k');

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
s = pd.Series([np.nan, np.nan, 1, 3, 4, np.nan, np.nan, 7, 8, np.nan, 10, np.nan, np.nan])
s

In [ ]:
not_null_idxs = s.notnull()[s.notnull()].index
valid_start = not_null_idxs[0]
valid_end = not_null_idxs[-1]
s[valid_start:valid_end] = s[valid_start:valid_end].fillna(method='ffill')
s

In [ ]:
symbols = ['AA', 'AABA', 'TSLA']
data = yf.download(symbols, start='1962-01-01', end='2024-03-23').drop(columns='Open')
data.head()

In [ ]:
new_cols = data.columns.map(lambda t: f'{t[1]}_{t[0]}'.lower().replace('_adj close', ''))
new_cols

In [ ]:
data.columns = new_cols
data.head()

In [ ]:
data.index = data.index.astype(str)
data.head()

In [ ]:
n = len(data)
nullsum = data.isnull().sum()
empties = nullsum[nullsum == n].index
empties

In [ ]:
data.drop(columns=empties, inplace=True)
data.head()

In [ ]:
def adj(sym, close, hilo):
    factor = sym / close
    #return factor
    hilo *= factor
    return hilo

In [ ]:
adj(data.aa, data.aa_close, data.aa_low)

In [ ]:
adj(data.aa, data.aa_close, data.aa_high)

In [ ]:
def get_pct_change(stock: pd.Series) -> pd.Series:
    return pd.Series(
        np.concatenate([[1], stock.values[1:] / stock.values[:-1]]), index=stock.index)

In [ ]:
get_pct_change(data.a)

In [ ]:
def get_next_day_ranges(close: pd.Series, low: pd.Series, high: pd.Series):
        c = close.values[:-1]
        l = low.values[1:]
        h = high.values[1:]
        next_day_min = pd.Series(np.concatenate([[1], l / c]), index=close.index)
        next_day_max = pd.Series(np.concatenate([[1], h / c]), index=close.index)
        return next_day_min, next_day_max

In [ ]:
# Test
close = pd.Series([  1,   2,   3,   4, 3.7])
low =   pd.Series([0.8, 1.8, 1.9, 4.1, 4.7])
high =  pd.Series([0.9, 2.2, 3.3, 4.4, 3.9])
get_next_day_ranges(close, low, high)

In [ ]:
import numpy as np


def random_password(n):
    opt = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQSRTUVWXYZ`1234567890-=[]\\;,./~!@#$%^&*()_+{}|:"<>?\'"'
    return ''.join(np.random.choice(list(opt), size=n, replace=True))

In [ ]:
random_password(20)

In [15]:
def convert_value(s):
    return round(float(s.replace('$', '').replace(',', '')))

In [20]:
def separate_accounts(fid):
    accounts = {
        account_name: fid[fid['Account Name'] == account_name]
        for account_name in fid['Account Name'].unique()}
    for acct in accounts:
        accounts[acct].index = accounts[acct].Symbol
        accounts[acct] = (
            accounts[acct]
            .rename(columns={'Current Value': acct})
            .drop(columns=['Account Name', 'Symbol']))
    return accounts

In [23]:
fidelity = pd.read_csv('~/Downloads/Portfolio_Positions_Dec-09-2025.csv')
#fidelity = fidelity[fidelity['Last Price'].notnull()]
#fidelity = fidelity[fidelity['Last Price'] != '--']
#fidelity = (fidelity[['Account Name', 'Symbol', 'Current Value']].dropna())
fidelity.head()

,Account Number,Account Name,Symbol,Description,Quantity,Last Price,Last Price Change,Current Value,Today's Gain/Loss Dollar,Today's Gain/Loss Percent,Total Gain/Loss Dollar,Total Gain/Loss Percent,Percent Of Account,Cost Basis Total,Average Cost Basis,Type
218520300,Rollover IRA,SPAXX**,HELD IN MONEY MARKET,NaN,NaN,NaN,$12204.09,NaN,NaN,NaN,NaN,15.42%,NaN,NaN,Cash,NaN
218520300,Rollover IRA,003CVR016,ABIOMED INC SHS,4.0,--,--,--,--,--,--,--,0.00%,--,--,Cash,NaN
218520300,Rollover IRA,RACE,FERRARI N V EUR0.01 NEW,32.0,$375.35,-$7.63,$12011.20,-$244.16,-2.00%,-$960.97,-7.41%,15.18%,$12972.17,$405.38,Cash,NaN
218520300,Rollover IRA,PSTG,PURE STORAGE INC CL A,88.0,$70.15,-$0.89,$6173.20,-$78.32,-1.26%,+$150.48,+2.49%,7.80%,$6022.72,$68.44,Cash,NaN
218520300,Rollover IRA,VEEV,VEEVA SYSTEMS INC,11.0,$232.00,-$7.05,$2552.00,-$77.55,-2.95%,-$41.14,-1.59%,3.23%,$2593.14,$235.74,Cash,NaN

In [17]:
fidelity['Current Value'] = (
    fidelity['Current Value']
    .apply(convert_value)
    .fillna(0)
    .astype(int))
fidelity.head()

          Account Name                   Symbol  Current Value
218520300         RACE  FERRARI N V EUR0.01 NEW           -244
218520300         PSTG    PURE STORAGE INC CL A            -78
218520300         VEEV        VEEVA SYSTEMS INC            -78
218520300           HD           HOME DEPOT INC            -70
218520300         DOCS        DOXIMITY INC CL A            -49

In [21]:
fidelity = fidelity[
    ((fidelity.Symbol != 'SPAXX**')
     & (fidelity.Symbol != 'Pending Activity'))]
fidelity = separate_accounts(fidelity)
fidelity

{'RACE':                          RACE
 Symbol
 FERRARI N V EUR0.01 NEW  -244
 FERRARI N V EUR0.01 NEW   -92,
 'PSTG':                        PSTG
 Symbol
 PURE STORAGE INC CL A   -78,
 'VEEV':                    VEEV
 Symbol
 VEEVA SYSTEMS INC   -78
 VEEVA SYSTEMS INC  -381,
 'HD':                 HD
 Symbol
 HOME DEPOT INC -70
 HOME DEPOT INC -46,
 'DOCS':                    DOCS
 Symbol
 DOXIMITY INC CL A   -49,
 'LEU':                      LEU
 Symbol
 CENTRUS ENERGY CORP  -46,
 'PTC':          PTC
 Symbol
 PTC INC  -27
 PTC INC   -4,
 'TYL':                         TYL
 Symbol
 TYLER TECHNOLOGIES INC  -14
 TYLER TECHNOLOGIES INC   -7,
 'SERV':                         SERV
 Symbol
 SERVE ROBOTICS INC COM   -12,
 'META':                                          META
 Symbol
 META PLATFORMS INC CLASS A COMMON STOCK   -10,
 'DKNG':                              DKNG
 Symbol
 DRAFTKINGS INC NEW COM CL A    -6,
 'DEO':                       DEO
 Symbol
 DIAGEO ADR REP 4 ORD   -3,
 'PDD':                                              PDD
 Symbol
 PDD HOLDINGS INC AMERICAN DEPOSITARY SHARES   -2
 PDD HOLDINGS INC AMERICAN DEPOSITARY SHARES   -5,
 'MASI':              MASI
 Symbol
 MASIMO CORP    -2,
 'NVDA':                         NVDA
 Symbol
 NVIDIA CORPORATION COM    -2,
 'CELH':                            CELH
 Symbol
 CELSIUS HLDGS INC COM NEW    -1
 CELSIUS HLDGS INC COM NEW   -90,
 'NVO':                                                    NVO
 Symbol
 NOVO NORDISK A/S ADR-EACH CNV INTO 1 CLASS B DKK1   -1,
 'JD':                                                  JD
 Symbol
 JD.COM INC SPON ADS EACH REPR 2 ORD SHS CLASS A  -1
 JD.COM INC SPON ADS EACH REPR 2 ORD SHS CLASS A  -1,
 'NKE':                           NKE
 Symbol
 NIKE INC CLASS B COM NPV   -1
 NIKE INC CLASS B COM NPV   -1,
 'DASTY':                                                DASTY
 Symbol
 DASSAULT SYSTEMES SPON ADR EACH REP 1 ORD SHS     -1
 DASSAULT SYSTEMES SPON ADR EACH REP 1 ORD SHS    -10,
 'EEM':                                          EEM
 Symbol
 ISHARES TRUST MSCI EMG MKTS ETF USD DIS    0,
 'RDY':                               RDY
 Symbol
 DR. REDDY S LABORATORIES-ADR    0,
 'NWN':                            NWN
 Symbol
 NORTHWEST NAT HLDG CO COM    0,
 'HDB':                                            HDB
 Symbol
 HDFC BANK LTD SPON ADS EACH REP 3 ORD SHS    0,
 'WIT':                                        WIT
 Symbol
 WIPRO LTD SPON ADR REP 1 ORD SHS INR2    0
 WIPRO LTD SPON ADR REP 1 ORD SHS INR2    0,
 'JPXN':                                         JPXN
 Symbol
 ISHARES TRUST JAPAN JPX NIKKEI 400 ETF     0,
 'CHTR':                                      CHTR
 Symbol
 CHARTER COMMUNICATIONS INC NEW CL A     0
 CHARTER COMMUNICATIONS INC NEW CL A     2,
 'COST':                            COST
 Symbol
 COSTCO WHOLESALE CORP COM     1,
 'PG':                            PG
 Symbol
 PROCTER AND GAMBLE CO COM   1,
 'MO':                   MO
 Symbol
 ALTRIA GROUP INC   2,
 'WING':                   WING
 Symbol
 WINGSTOP INC COM     2,
 'ZBRA':                                      ZBRA
 Symbol
 ZEBRA TECHNOLOGIES CORPORATION CL A     2
 ZEBRA TECHNOLOGIES CORPORATION CL A     3,
 'OPEN':                                OPEN
 Symbol
 OPENDOOR TECHNOLOGIES INC COM     2,
 'NLR':                                    NLR
 Symbol
 VANECK ETF TRUST URANIUM AND NUCL    2
 VANECK ETF TRUST URANIUM AND NUCL    0,
 'CEG':                                CEG
 Symbol
 CONSTELLATION ENERGY CORP COM    3,
 'ABNB':                      ABNB
 Symbol
 AIRBNB INC COM CL A     3,
 'ELF':                       ELF
 Symbol
 E L F BEAUTY INC COM    4,
 'LIN':                         LIN
 Symbol
 LINDE PLC COM EUR0.001    5
 LINDE PLC COM EUR0.001   32,
 'NET':                          NET
 Symbol
 CLOUDFLARE INC CL A COM    6,
 'NICE':                                        NICE
 Symbol
 NICE LTD ADR-EACH CNV INTO 1 ORD ILS1     7
 NICE LTD ADR-EACH CNV INTO 1 ORD ILS1     7,
 'GRMN':                          GRMN
 Symbol
 GARMIN LTD COM CHF10.00     8
 GARMIN LTD COM CHF10.00    73,
 'CLPBY':                                          CLPBY
 Symbol
 COLOPLAST SPON ADS EACH REPR 0.1 OD SHS      8,
 'ORCL':              ORCL
 Symbol
 ORACLE CORP    16
 ORACLE CORP    60,
 'TSLA':                TSLA
 Symbol
 TESLA INC COM    22,
 'KNSL':                            KNSL
 Symbol
 KINSALE CAP GROUP INC COM    35,
 'BTG':                                                    BTG
 Symbol
 B2GOLD CORP COM ISIN #CA11777Q2099 SEDOL #B29VFC4   67,
 'SMLR':                                     SMLR
 Symbol
 SEMLER SCIENTIFIC INC COM USD0.001    79
 SEMLER SCIENTIFIC INC COM USD0.001   186,
 'BYDDY':                                  BYDDY
 Symbol
 BYD CO UNSP ADR EACH REPR 2 ORD    -70,
 'BAESY':                                BAESY
 Symbol
 BAE SYSTEMS PLC SPONSORED ADR    -35
 BAE SYSTEMS PLC SPONSORED ADR     -3,
 'MA':                               MA
 Symbol
 MASTERCARD INCORPORATED CL A -29,
 'FTNT':                            FTNT
 Symbol
 FORTINET INC COM USD0.001    -6,
 'CP':                                                     CP
 Symbol
 CANADIAN PAC KANS CITY LTD ISIN #CA13646K1084 S...  -5,
 'V':           V
 Symbol
 VISA INC -5,
 'MDB':                   MDB
 Symbol
 MONGODB INC CL A   -5,
 'VLTO':                       VLTO
 Symbol
 VERALTO CORP COM SHS    -4,
 'RMD':             RMD
 Symbol
 RESMED INC   -4,
 'HON':                                       HON
 Symbol
 HONEYWELL INTERNATIONAL INC COM USD1   -2,
 'CPNG':                   CPNG
 Symbol
 COUPANG INC CL A    -1,
 'KTEC':                                   KTEC
 Symbol
 KRANESHARES TRUST HANG SENG TECH    -1,
 'TTC':          TTC
 Symbol
 TORO CO   -1,
 'FBIN':                                    FBIN
 Symbol
 FORTUNE BRANDS INNOVATIONS INC CO    -1,
 'QSR':                                                     QSR
 Symbol
 RESTAURANT BRANDS INTERNATIONAL INC COM NPV ISI...   -1,
 'DIS':                     DIS
 Symbol
 DISNEY WALT CO COM   -1,
 'SPY':                                                     SPY
 Symbol
 SPDR S&P500 ETF TRUST TRUST UNIT DEPOSITARY REC...   -1,
 'IVV':                           IVV
 Symbol
 ISHARES CORE S&P 500 ETF   -1,
 'KR':                        KR
 Symbol
 KROGER CO COM USD1.00   0,
 'IEFA':                                   IEFA
 Symbol
 ISHARES TRUST CORE MSCI EAFE ETF     0,
 'GEHC':                                              GEHC
 Symbol
 GE HEALTHCARE TECHNOLOGIES INC COMMON STOCK     0,
 'GRAB':                                             GRAB
 Symbol
 GRAB HLDGS LTD CL A ORD ISIN #KYG4124C1096     0,
 'RGTI':                                     RGTI
 Symbol
 RIGETTI COMPUTING INC COMMON STOCK     0
 RIGETTI COMPUTING INC COMMON STOCK    -2,
 'GGEI':                          GGEI
 Symbol
 GREEN GIANT INC COM NEW     0,
 'IBN':                                                  IBN
 Symbol
 ICICI BANK LIMITED SPON ADR EACH REPR 2 ORD SHS    0,
 'NFTY':                                                  NFTY
 Symbol
 FIRST TR EXCH TRD ALPHDX FD II INDIA NFTY50 EQW     0,
 'IONQ':               IONQ
 Symbol
 IONQ INC COM     0,
 'SNPS':               SNPS
 Symbol
 SYNOPSYS INC     0,
 'VTRS':                  VTRS
 Symbol
 VIATRIS INC COM     0,
 'UBSI':                        UBSI
 Symbol
 UNITED BANKSHARES INC     0,
 'COF':                                         COF
 Symbol
 CAPITAL ONE FINANCIAL CORP COM USD0.01    0,
 'ONON':                             ONON
 Symbol
 ON HLDNG AG CHF0.1 CLASS A     0,
 'QTUM':                                   QTUM
 Symbol
 ETF SER SOLUTIONS DEFIANCE QUANT     0,
 'BXP':              BXP
 Symbol
 BXP INC COM    0,
 'UVV':                 UVV
 Symbol
 UNIVERSAL CORP    1,
 'B':                                                     B
 Symbol
 BARRICK MINING CORPORATION COM NPV ISIN #CA0684...  1,
 'CMG':                             CMG
 Symbol
 CHIPOTLE MEXICAN GRILL INC    1,
 'TTAN':                            TTAN
 Symbol
 SERVICETITAN INC SHS CL A     1,
 'MSFT':                 MSFT
 Symbol
 MICROSOFT CORP     1,
 'NOW':                              NOW
 Symbol
 SERVICENOW INC COM USD0.001    1,
 'CART':                    CART
 Symbol
 MAPLEBEAR INC COM     2,
 'RVLV':                         RVLV
 Symbol
 REVOLVE GROUP INC CL A     2,
 'GDX':                                       GDX
 Symbol
 VANECK ETF TR VANECK GOLD MINERS ETF    3,
 'PGR':                       PGR
 Symbol
 PROGRESSIVE CORP COM    3,
 'MMYT':                           MMYT
 Symbol
 MAKEMYTRIP LTD USD0.0005     4,
 'BROS':                      BROS
 Symbol
 DUTCH BROS INC CL A     4,
 'FNV':                                                     FNV
 Symbol
 FRANCO NEV CORP COM ISIN #CA3518581051 SEDOL #B...    7,
 'SAM':                          SAM
 Symbol
 BOSTON BEER COMPANY INC    9,
 'SAP':                    SAP
 Symbol
 SAP ADR REP 1 ORD   10,
 'ADBE':                ADBE
 Symbol
 ADOBE INC COM    10,
 'DASH':                    DASH
 Symbol
 DOORDASH INC CL A    18,
 'KD':                                 KD
 Symbol
 KYNDRYL HLDGS INC COMMON STOCK  41,
 'IBIT':                            IBIT
 Symbol
 ISHARES BITCOIN TRUST ETF   402,
 'RKLB':                      RKLB
 Symbol
 ROCKET LAB CORP COM   585
 ROCKET LAB CORP COM    21,
 'INFY':                                          INFY
 Symbol
 INFOSYS LTD SPON ADR EACH REP 1 ORD SHS     0,
 'PTON':                                   PTON
 Symbol
 PELOTON INTERACTIVE INC CL A COM     2}

In [26]:
DATA = '../daily/data'

In [27]:
import pickle

with open(f'{DATA}/all_symbols.pkl', 'rb') as f:
    all_stocks = pickle.load(f)
    print(len(all_stocks))

11487

<a href="https://stockti.com/stocks/sp500">S&P Ticker Source</a>

In [28]:
sp500 = '''1 	AAPL 	Apple Inc 	$304.99 	+0.91% 	36.2 	Technology 	4.44T
2 	ABBV 	Abbvie Inc 	$214.50 	+1.04% 	88.1 	Biotechnology 	372.39B
3 	ABT 	Abbott Laboratories 	$87.77 	-0.69% 	23.4 	Health Care 	146.70B
4 	ADI 	Analog Devices Inc 	$384.21 	-3.48% 	75.7 	Semiconductors 	205.02B
5 	AMAT 	Applied Materials Inc 	$427.36 	+0.12% 	43.7 	Semiconductors 	342.16B
6 	AMD 	Advanced Micro Devices Inc 	$449.59 	+0.45% 	138.1 	Semiconductors 	691.54B
7 	AMGN 	Amgen Inc 	$337.42 	+1.76% 	23.0 	Biotechnology 	179.23B
8 	AMZN 	Amazon.com Inc 	$268.46 	+1.30% 	31.1 	Retail 	2.82T
9 	ANET 	Arista Networks Inc 	$148.59 	+5.77% 	48.3 	Communications 	179.68B
10 	APH 	Amphenol Corp-Cl A 	$124.86 	+1.47% 	34.9 	Electrical Equipment 	155.69B
11 	APP 	Applovin Corp-Class A 	$485.89 	+0.75% 	41.2 	Technology 	163.14B
12 	AVGO 	Broadcom Inc. 	$414.57 	-0.76% 	81.0 	Semiconductors 	2.02T
13 	AXP 	American Express Co 	$309.70 	-0.04% 	19.1 	Financial Services 	214.68B
14 	BA 	Boeing Co. 	$219.61 	-1.17% 	77.6 	Aerospace & Defense 	175.91B
15 	BAC 	Bank of America Corp 	$51.49 	+0.51% 	11.1 	Banking 	350.86B
16 	BKNG 	Booking Holdings Inc 	$159.68 	+1.74% 	19.3 	Hotels, Restaurants & Leisure 	119.04B
17 	BLK 	Blackrock Inc 	$1,063.75 	+1.16% 	28.7 	Financial Services 	179.78B
18 	BMY 	Bristol-Myers Squibb Co 	$59.55 	+1.73% 	19.2 	Pharmaceuticals 	114.93B
19 	BRK.B 	Berkshire Hathaway Inc 	$479.98 	-0.19% 	14.4 	Financial Services 	1.04T
20 	BX 	Blackstone Inc 	$118.57 	+1.49% 	47.2 	Financial Services 	144.00B
21 	C 	Citigroup Inc 	$125.22 	+0.32% 	13.2 	Banking 	211.65B
22 	CAT 	Caterpillar Inc. 	$865.95 	-0.76% 	43.2 	Machinery 	407.24B
23 	CB 	Chubb Ltd 	$330.26 	+0.57% 	11.1 	Insurance 	125.66B
24 	COF 	Capital One Financial Corp 	$186.66 	-0.30% 	36.2 	Financial Services 	116.65B
25 	COP 	Conocophillips 	$120.55 	-1.48% 	20.2 	Energy 	147.54B
26 	COST 	Costco Wholesale Corp. 	$1,050.45 	-2.19% 	54.3 	Retail 	464.42B
27 	CRM 	Salesforce Inc 	$176.31 	-2.10% 	18.6 	Technology 	139.01B
28 	CRWD 	Crowdstrike Holdings Inc - A 	$648.23 	-0.29% 	— 	Technology 	151.24B
29 	CSCO 	Cisco Systems Inc 	$118.20 	+3.37% 	38.2 	Communications 	456.33B
30 	CVS 	Cvs Health Corp 	$93.32 	+0.04% 	42.3 	Health Care 	124.08B
31 	CVX 	Chevron Corporation 	$191.01 	-0.17% 	34.3 	Energy 	377.85B
32 	DE 	Deere & Co 	$531.35 	-5.19% 	31.6 	Machinery 	152.28B
33 	DELL 	Dell Technologies -C 	$252.80 	+4.06% 	26.6 	Technology 	157.88B
34 	DIS 	Walt Disney Co 	$103.58 	-0.48% 	16.0 	Media 	179.07B
35 	ETN 	Eaton Corp Plc 	$381.51 	+0.48% 	38.8 	Electrical Equipment 	154.77B
36 	GE 	GE Aerospace 	$301.76 	+0.53% 	34.7 	Aerospace & Defense 	299.72B
37 	GEV 	Ge Vernova Inc 	$1,043.82 	+1.88% 	31.3 	Electrical Equipment 	293.05B
38 	GILD 	Gilead Sciences Inc 	$130.50 	-0.15% 	17.4 	Biotechnology 	160.50B
39 	GLW 	Corning Inc 	$191.89 	+6.20% 	93.4 	Electrical Equipment 	169.04B
40 	GOOG 	Alphabet Inc-Cl C 	$383.47 	-0.37% 	30.0 	Media 	4.80T
41 	GOOGL 	Alphabet Inc 	$387.66 	-0.32% 	30.0 	Media 	4.80T
42 	GS 	Goldman Sachs Group 	$988.17 	+0.62% 	15.4 	Financial Services 	277.99B
43 	HD 	Home Depot Inc 	$313.78 	+1.03% 	21.0 	Retail 	297.77B
44 	HON 	Honeywell International Inc 	$223.80 	+2.95% 	30.6 	Industrial Conglomerates 	137.96B
45 	IBKR 	Interactive Brokers Gro-Cl A 	$83.83 	+0.05% 	142.2 	Financial Services 	147.58B
46 	IBM 	Intl Business Machines Corp 	$252.97 	+12.43% 	19.1 	Technology 	205.06B
47 	INTC 	Intel Corp 	$118.50 	-0.39% 	— 	Semiconductors 	551.20B
48 	ISRG 	Intuitive Surgical Inc 	$439.80 	-2.06% 	51.1 	Health Care 	152.10B
49 	JNJ 	Johnson & Johnson 	$231.73 	+1.05% 	26.1 	Pharmaceuticals 	549.56B
50 	JPM 	JPMorgan Chase & Co 	$303.00 	+0.34% 	13.6 	Banking 	798.43B
51 	KLAC 	Kla Corp 	$1,842.18 	+0.69% 	50.5 	Semiconductors 	235.69B
52 	KO 	Coca-Cola Co. 	$81.17 	-0.47% 	25.4 	Beverages 	348.46B
53 	LIN 	Linde Plc 	$514.51 	+1.56% 	33.1 	Chemicals 	234.13B
54 	LLY 	Eli Lilly and Co. 	$1,041.65 	+2.24% 	37.5 	Pharmaceuticals 	946.93B
55 	LMT 	Lockheed Martin Corp 	$522.79 	+0.04% 	24.8 	Aerospace & Defense 	119.04B
56 	LOW 	Lowe'S Cos Inc 	$217.41 	-1.65% 	18.5 	Retail 	122.93B
57 	LRCX 	Lam Research Corp 	$302.24 	+3.48% 	52.7 	Semiconductors 	353.58B
58 	MA 	Mastercard Inc 	$499.62 	+0.32% 	28.3 	Financial Services 	440.72B
59 	MCD 	McDonalds Corp. 	$284.18 	+1.40% 	22.6 	Hotels, Restaurants & Leisure 	196.23B
60 	META 	Meta Platforms Inc 	$607.38 	+0.38% 	22.2 	Media 	1.57T
61 	MO 	Altria Group Inc 	$73.71 	+0.52% 	15.1 	Tobacco 	121.26B
62 	MRK 	Merck & Co. Inc. 	$115.88 	+2.55% 	31.2 	Pharmaceuticals 	278.45B
63 	MS 	Morgan Stanley 	$200.51 	+1.39% 	16.8 	Financial Services 	304.86B
64 	MSFT 	Microsoft Corp 	$419.09 	-0.47% 	24.7 	Technology 	3.09T
65 	MU 	Micron Technology Inc 	$762.10 	+4.11% 	34.4 	Semiconductors 	829.08B
66 	NEE 	Nextera Energy Inc 	$89.69 	+1.61% 	23.9 	Utilities 	195.77B
67 	NEM 	Newmont Corp 	$108.33 	+0.88% 	13.8 	Metals & Mining 	116.43B
68 	NFLX 	Netflix Inc 	$89.30 	+1.37% 	27.3 	Media 	365.69B
69 	NVDA 	NVIDIA Corp 	$219.51 	-1.77% 	45.8 	Semiconductors 	5.50T
70 	ORCL 	Oracle Corporation 	$189.77 	+0.86% 	33.9 	Technology 	548.98B
71 	PANW 	Palo Alto Networks Inc 	$252.92 	+2.54% 	151.6 	Technology 	194.38B
72 	PEP 	PepsiCo Inc. 	$148.85 	-0.29% 	23.3 	Beverages 	203.42B
73 	PFE 	Pfizer Inc. 	$25.95 	+0.62% 	19.3 	Pharmaceuticals 	144.48B
74 	PG 	Procter & Gamble Co 	$143.40 	+0.67% 	19.9 	Consumer products 	331.13B
75 	PGR 	Progressive Corp 	$198.97 	-1.79% 	10.1 	Insurance 	116.71B
76 	PLTR 	Palantir Technologies 	$137.42 	+0.19% 	140.8 	Technology 	321.22B
77 	PM 	Philip Morris International 	$188.46 	-0.09% 	26.6 	Tobacco 	295.52B
78 	QCOM 	Qualcomm Inc 	$213.41 	+5.38% 	21.8 	Semiconductors 	216.36B
79 	RTX 	Rtx Corp 	$175.98 	+0.65% 	31.8 	Aerospace & Defense 	230.53B
80 	SBUX 	Starbucks Corp 	$104.13 	-2.23% 	81.0 	Hotels, Restaurants & Leisure 	121.09B
81 	SCHW 	Schwab (Charles) Corp 	$90.41 	+0.33% 	16.8 	Financial Services 	158.28B
82 	SNDK 	Sandisk Corp 	$1,542.24 	+10.75% 	45.4 	Technology 	204.77B
83 	SPGI 	S&P Global Inc 	$415.73 	-0.31% 	24.9 	Financial Services 	119.06B
84 	STX 	Seagate Technology Holdings 	$810.46 	+7.91% 	75.9 	Technology 	180.45B
85 	SYK 	Stryker Corp 	$313.50 	-2.49% 	35.2 	Health Care 	117.42B
86 	T 	AT&T Inc. 	$25.34 	+1.64% 	8.0 	Telecommunication 	171.90B
87 	TJX 	Tjx Companies Inc 	$157.46 	-1.10% 	29.7 	Retail 	163.11B
88 	TMO 	Thermo Fisher Scientific Inc 	$449.37 	-0.54% 	23.8 	Life Sciences Tools & Services 	163.24B
89 	TMUS 	T-Mobile Us Inc 	$190.90 	+0.39% 	19.1 	Telecommunication 	201.27B
90 	TSLA 	Tesla Inc 	$417.85 	+0.14% 	431.1 	Automobiles 	1.66T
91 	TXN 	Texas Instruments Inc 	$298.39 	-2.13% 	51.4 	Semiconductors 	275.59B
92 	UBER 	Uber Technologies Inc. 	$73.61 	-1.33% 	17.9 	Road & Rail 	152.85B
93 	UNH 	UnitedHealth Group Inc 	$382.48 	-0.21% 	29.8 	Health Care 	358.78B
94 	UNP 	Union Pacific Corp 	$265.44 	-0.14% 	22.2 	Road & Rail 	159.91B
95 	V 	Visa Inc 	$331.12 	+0.11% 	27.2 	Financial Services 	605.48B
96 	VZ 	Verizon Communications 	$48.27 	+0.94% 	11.3 	Telecommunication 	196.50B
97 	WDC 	Western Digital Corp 	$486.46 	+5.84% 	25.9 	Technology 	168.60B
98 	WFC 	Wells Fargo & Co 	$75.92 	+0.15% 	10.4 	Banking 	225.81B
99 	WMT 	Walmart Inc 	$121.34 	-7.27% 	47.9 	Retail 	1.05T
100 	XOM 	Exxon Mobil Corp 	$155.29 	-0.63% 	25.0 	Energy 	633.27B
101 	DHR 	Danaher Corp 	$173.33 	+1.29% 	31.1 	Life Sciences Tools & Services 	114.81B
102 	VRTX 	Vertex Pharmaceuticals Inc 	$433.54 	+0.72% 	26.4 	Biotechnology 	114.32B
103 	PWR 	Quanta Services Inc 	$716.91 	+0.98% 	102.5 	Construction 	113.26B
104 	CME 	Cme Group Inc 	$289.29 	-0.29% 	25.5 	Financial Services 	108.73B
105 	PH 	Parker Hannifin Corp 	$864.73 	+0.62% 	31.0 	Machinery 	108.04B
106 	INTU 	Intuit Inc 	$307.07 	-20.02% 	24.7 	Technology 	107.26B
107 	SO 	Southern Co/The 	$94.24 	+0.66% 	23.9 	Utilities 	104.47B
108 	HWM 	Howmet Aerospace Inc 	$259.89 	-0.51% 	59.7 	Aerospace & Defense 	104.17B
109 	TT 	Trane Technologies Plc 	$447.64 	-0.90% 	35.6 	Building 	103.14B
110 	ACN 	Accenture Plc-Cl A 	$177.87 	-0.75% 	13.3 	Technology 	101.72B
111 	CEG 	Constellation Energy 	$285.83 	+1.62% 	26.2 	Utilities 	99.42B
112 	MDT 	Medtronic Plc 	$78.15 	+0.00% 	21.4 	Health Care 	98.82B
113 	CMI 	Cummins Inc 	$638.78 	-4.64% 	33.9 	Machinery 	96.29B
114 	SNPS 	Synopsys Inc 	$503.98 	+1.01% 	87.3 	Technology 	96.14B
115 	ADBE 	Adobe Inc 	$244.10 	-3.66% 	13.3 	Technology 	95.80B
116 	DUK 	Duke Energy Corp 	$124.66 	+0.69% 	18.6 	Utilities 	95.69B
117 	CDNS 	Cadence Design Sys Inc 	$358.46 	+2.16% 	81.6 	Technology 	95.55B
118 	WMB 	Williams Cos Inc 	$77.52 	-0.46% 	34.0 	Energy 	95.01B
119 	HCA 	Hca Healthcare Inc 	$392.56 	-1.04% 	13.9 	Health Care 	94.17B
120 	NOW 	Servicenow Inc 	$99.69 	-3.49% 	53.1 	Technology 	93.33B
121 	MAR 	Marriott International -Cl A 	$370.56 	+0.22% 	36.0 	Hotels, Restaurants & Leisure 	93.08B
122 	BK 	Bank Of New York Mellon Corp 	$137.16 	+0.62% 	15.6 	Financial Services 	92.86B
123 	GD 	General Dynamics Corp 	$338.71 	-0.31% 	21.1 	Aerospace & Defense 	91.75B
124 	MCK 	Mckesson Corp 	$766.50 	+1.57% 	19.2 	Health Care 	91.26B
125 	FCX 	Freeport-Mcmoran Inc 	$62.31 	+2.37% 	40.8 	Metals & Mining 	89.85B
126 	FDX 	Fedex Corp 	$388.91 	+0.54% 	20.0 	Logistics & Transportation 	89.56B
127 	FTNT 	Fortinet Inc 	$129.46 	-0.42% 	45.6 	Technology 	89.20B
128 	CMCSA 	Comcast Corp-Class A 	$25.08 	+0.80% 	4.7 	Telecommunication 	88.89B
129 	ICE 	Intercontinental Exchange In 	$151.49 	-0.13% 	22.4 	Financial Services 	88.08B
130 	WM 	Waste Management Inc 	$217.75 	-0.84% 	31.5 	Commercial Services & Supplies 	87.87B
131 	JCI 	Johnson Controls Internation 	$135.47 	-1.66% 	24.7 	Building 	87.09B
132 	KKR 	Kkr & Co Inc 	$94.76 	+0.45% 	36.7 	Financial Services 	87.07B
133 	ELV 	Elevance Health Inc 	$389.82 	-1.61% 	16.4 	Health Care 	85.87B
134 	PNC 	Pnc Financial Services Group 	$218.37 	+0.71% 	11.9 	Banking 	85.51B
135 	ADP 	Automatic Data Processing 	$220.08 	-0.28% 	19.7 	Professional Services 	85.43B
136 	MNST 	Monster Beverage Corp 	$86.32 	-0.64% 	44.6 	Beverages 	84.99B
137 	CSX 	Csx Corp 	$45.90 	-0.09% 	27.8 	Road & Rail 	84.73B
138 	UPS 	United Parcel Service-Cl B 	$98.25 	-0.63% 	15.9 	Logistics & Transportation 	83.66B
139 	SLB 	Slb Ltd 	$57.25 	-0.05% 	25.0 	Energy 	83.05B
140 	USB 	Us Bancorp 	$54.56 	+0.11% 	10.6 	Banking 	82.92B
141 	ABNB 	Airbnb Inc-Class A 	$134.25 	-0.96% 	32.0 	Hotels, Restaurants & Leisure 	80.56B
142 	BSX 	Boston Scientific Corp 	$57.15 	+0.85% 	22.0 	Health Care 	78.48B
143 	MDLZ 	Mondelez International Inc-A 	$61.50 	-0.55% 	30.0 	Food Products 	78.46B
144 	APO 	Apollo Global Management Inc 	$130.90 	-1.01% 	68.3 	Financial Services 	78.13B
145 	NOC 	Northrop Grumman Corp 	$551.58 	-0.11% 	17.1 	Aerospace & Defense 	78.08B
146 	CI 	The Cigna Group 	$282.02 	-0.38% 	12.3 	Health Care 	77.01B
147 	MPWR 	Monolithic Power Systems Inc 	$1,561.25 	+0.51% 	112.8 	Semiconductors 	76.80B
148 	MCO 	Moody'S Corp 	$445.37 	+0.25% 	30.5 	Financial Services 	76.16B
149 	MMM 	3M Co 	$151.60 	+1.22% 	27.3 	Industrial Conglomerates 	76.12B
150 	EMR 	Emerson Electric Co 	$134.90 	+1.54% 	30.9 	Electrical Equipment 	75.51B
151 	ORLY 	O'Reilly Automotive Inc 	$92.34 	+0.13% 	28.7 	Retail 	74.82B
152 	KMI 	Kinder Morgan Inc 	$33.50 	-0.27% 	22.5 	Energy 	74.65B
153 	CVNA 	Carvana Co 	$64.39 	-0.80% 	51.7 	Retail 	74.51B
154 	NXPI 	Nxp Semiconductors Nv 	$299.38 	-3.47% 	28.0 	Semiconductors 	74.27B
155 	SHW 	Sherwin-Williams Co/The 	$309.34 	+0.53% 	28.6 	Chemicals 	74.26B
156 	EOG 	Eog Resources Inc 	$139.98 	-1.17% 	13.5 	Energy 	74.17B
157 	REGN 	Regeneron Pharmaceuticals 	$642.59 	-1.10% 	16.7 	Biotechnology 	73.89B
158 	DDOG 	Datadog Inc - Class A 	$218.04 	+2.73% 	542.3 	Technology 	73.57B
159 	HOOD 	Robinhood Markets Inc - A 	$75.92 	+0.21% 	38.3 	Financial Services 	72.74B
160 	VLO 	Valero Energy Corp 	$241.09 	-5.00% 	17.3 	Energy 	72.68B
161 	MPC 	Marathon Petroleum Corp 	$248.43 	-3.85% 	15.7 	Energy 	72.64B
162 	HLT 	Hilton Worldwide Holdings In 	$322.76 	-0.34% 	46.7 	Hotels, Restaurants & Leisure 	71.98B
163 	ITW 	Illinois Tool Works 	$249.93 	-0.34% 	22.7 	Machinery 	71.27B
164 	NSC 	Norfolk Southern Corp 	$311.44 	-0.13% 	26.7 	Road & Rail 	71.16B
165 	CL 	Colgate-Palmolive Co 	$90.44 	+0.10% 	33.9 	Consumer products 	70.83B
166 	GM 	General Motors Co 	$77.21 	+1.41% 	27.6 	Automobiles 	70.10B
167 	AEP 	American Electric Power 	$129.61 	+0.57% 	19.2 	Utilities 	69.97B
168 	CRH 	Crh Plc 	$101.03 	-0.41% 	19.0 	Construction 	69.84B
169 	RCL 	Royal Caribbean Cruises Ltd 	$260.32 	+2.53% 	15.6 	Hotels, Restaurants & Leisure 	69.81B
170 	FIX 	Comfort Systems Usa Inc 	$1,835.33 	-0.01% 	56.9 	Construction 	69.67B
171 	ECL 	Ecolab Inc 	$250.18 	+0.62% 	32.9 	Chemicals 	69.32B
172 	ROST 	Ross Stores Inc 	$217.19 	-0.28% 	32.2 	Retail 	69.07B
173 	PSX 	Phillips 66 	$174.05 	-2.95% 	16.7 	Energy 	68.76B
174 	AON 	Aon Plc-Class A 	$324.22 	+0.96% 	17.2 	Insurance 	67.77B
175 	WBD 	Warner Bros Discovery Inc 	$27.10 	-1.17% 	— 	Media 	67.64B
176 	CTAS 	Cintas Corp 	$172.36 	+0.58% 	34.8 	Commercial Services & Supplies 	67.47B
177 	DASH 	Doordash Inc - A 	$159.27 	-0.91% 	72.1 	Hotels, Restaurants & Leisure 	66.76B
178 	APD 	Air Products & Chemicals Inc 	$290.19 	+0.35% 	31.6 	Chemicals 	66.68B
179 	MSI 	Motorola Solutions Inc 	$400.24 	+1.09% 	31.7 	Communications 	66.14B
180 	RSG 	Republic Services Inc 	$208.09 	-1.94% 	29.7 	Commercial Services & Supplies 	64.49B
181 	TDG 	Transdigm Group Inc 	$1,209.32 	+0.94% 	30.7 	Aerospace & Defense 	63.99B
182 	TRV 	Travelers Cos Inc/The 	$307.23 	+0.09% 	8.4 	Insurance 	63.82B
183 	BKR 	Baker Hughes Co 	$65.80 	-1.48% 	20.4 	Energy 	63.61B
184 	NKE 	Nike Inc. 	$44.39 	+0.45% 	27.8 	Textiles, Apparel & Luxury Goods 	62.57B
185 	URI 	United Rentals Inc 	$932.18 	-0.44% 	24.3 	Trading Companies & Distributors 	60.95B
186 	KEYS 	Keysight Technologies In 	$337.55 	-1.32% 	62.4 	Electrical Equipment 	60.03B
187 	SRE 	Sempra 	$91.55 	+0.10% 	30.7 	Utilities 	60.00B
188 	GWW 	Ww Grainger Inc 	$1,239.26 	-0.39% 	33.7 	Trading Companies & Distributors 	59.97B
189 	AFL 	Aflac Inc 	$117.81 	+0.50% 	12.8 	Insurance 	59.23B
190 	TEL 	Te Connectivity Plc 	$202.57 	+0.59% 	20.3 	Electrical Equipment 	58.89B
191 	TFC 	Truist Financial Corp 	$47.89 	-0.23% 	10.6 	Banking 	58.51B
192 	OXY 	Occidental Petroleum Corp 	$58.83 	-0.07% 	12.3 	Energy 	58.44B
193 	PCAR 	Paccar Inc 	$109.34 	-2.06% 	23.6 	Machinery 	58.31B
194 	OKE 	Oneok Inc 	$92.62 	+0.51% 	16.3 	Energy 	57.60B
195 	TRGP 	Targa Resources Corp 	$270.24 	-0.17% 	26.9 	Energy 	57.41B
196 	LHX 	L3Harris Technologies Inc 	$306.33 	-0.91% 	32.6 	Aerospace & Defense 	56.52B
197 	FANG 	Diamondback Energy Inc 	$200.97 	-1.64% 	198.4 	Energy 	56.34B
198 	COIN 	Coinbase Global Inc. 	$193.56 	+1.19% 	69.9 	Financial Services 	55.99B
199 	ALL 	Allstate Corp 	$214.44 	-3.40% 	4.6 	Insurance 	55.90B
200 	DVN 	Devon Energy Corp 	$47.11 	-2.79% 	24.5 	Energy 	55.64B
201 	AZO 	Autozone Inc 	$3,438.18 	+0.55% 	22.7 	Retail 	55.40B
202 	CTVA 	Corteva Inc 	$79.04 	+0.30% 	47.3 	Chemicals 	54.98B
203 	TGT 	Target Corp 	$126.15 	+3.12% 	14.8 	Retail 	54.78B
204 	D 	Dominion Energy Inc 	$68.29 	+0.83% 	18.4 	Utilities 	54.39B
205 	F 	Ford Motor Co 	$13.67 	+3.40% 	— 	Automobiles 	53.97B
206 	CARR 	Carrier Global Corp 	$62.18 	-2.22% 	41.0 	Building 	53.71B
207 	TER 	Teradyne Inc 	$353.44 	+2.64% 	61.9 	Semiconductors 	52.89B
208 	AME 	Ametek Inc 	$223.17 	-0.69% 	34.2 	Electrical Equipment 	52.24B
209 	NUE 	Nucor Corp 	$226.44 	+0.34% 	29.6 	Metals & Mining 	51.68B
210 	NDAQ 	Nasdaq Inc 	$90.41 	+0.44% 	26.8 	Financial Services 	51.28B
211 	MCHP 	Microchip Technology Inc 	$91.11 	-3.10% 	222.5 	Semiconductors 	51.17B
212 	ETR 	Entergy Corp 	$112.27 	+0.30% 	28.3 	Utilities 	50.95B
213 	EBAY 	Ebay Inc 	$117.13 	-1.54% 	24.9 	Retail 	50.88B
214 	AJG 	Arthur J Gallagher & Co 	$207.41 	+1.87% 	31.4 	Insurance 	50.59B
215 	MET 	Metlife Inc 	$84.30 	+2.17% 	14.0 	Insurance 	50.55B
216 	EA 	Electronic Arts Inc 	$201.87 	+0.14% 	56.6 	Media 	50.20B
217 	COR 	Cencora Inc 	$265.44 	+0.26% 	19.7 	Health Care 	50.14B
218 	ROK 	Rockwell Automation Inc 	$440.25 	+0.92% 	45.8 	Electrical Equipment 	49.84B
219 	FAST 	Fastenal Co 	$43.53 	-0.34% 	38.3 	Trading Companies & Distributors 	49.79B
220 	ADSK 	Autodesk Inc 	$240.19 	-1.41% 	44.0 	Technology 	49.46B
221 	XEL 	Xcel Energy Inc 	$80.20 	+0.43% 	23.3 	Utilities 	48.64B
222 	VST 	Vistra Corp 	$149.08 	+3.53% 	49.9 	Utilities 	47.10B
223 	EW 	Edwards Lifesciences Corp 	$83.20 	+0.28% 	42.8 	Health Care 	46.94B
224 	DAL 	Delta Air Lines Inc 	$75.65 	+2.06% 	10.3 	Airlines 	46.19B
225 	CAH 	Cardinal Health Inc 	$200.61 	+0.69% 	29.5 	Health Care 	45.84B
226 	WAB 	Wabtec Corp 	$255.16 	-1.53% 	37.8 	Machinery 	45.72B
227 	ON 	On Semiconductor 	$109.61 	-0.54% 	78.8 	Semiconductors 	45.20B
228 	TTWO 	Take-Two Interactive Softwre 	$238.08 	+0.62% 	— 	Media 	44.71B
229 	EXC 	Exelon Corp 	$45.35 	+1.07% 	16.0 	Utilities 	44.39B
230 	HPE 	Hewlett Packard Enterprise 	$33.97 	+0.50% 	— 	Technology 	44.01B
231 	GRMN 	Garmin Ltd 	$239.78 	+0.97% 	25.3 	Consumer products 	43.87B
232 	XYZ 	Block Inc 	$68.65 	-3.16% 	52.8 	Financial Services 	42.57B
233 	FITB 	Fifth Third Bancorp 	$49.16 	+0.61% 	19.5 	Banking 	42.47B
234 	AMP 	Ameriprise Financial Inc 	$450.57 	-1.47% 	10.9 	Financial Services 	42.44B
235 	STT 	State Street Corp 	$153.69 	-0.25% 	13.8 	Financial Services 	42.35B
236 	IDXX 	Idexx Laboratories Inc 	$553.07 	-0.09% 	38.2 	Health Care 	41.88B
237 	MSCI 	Msci Inc 	$582.34 	+0.06% 	31.7 	Financial Services 	41.82B
238 	ODFL 	Old Dominion Freight Line 	$207.69 	-1.02% 	41.5 	Road & Rail 	41.77B
239 	YUM 	Yum! Brands Inc 	$154.32 	+1.05% 	23.9 	Hotels, Restaurants & Leisure 	41.52B
240 	CMG 	Chipotle Mexican Grill Inc 	$32.80 	-0.49% 	28.5 	Hotels, Restaurants & Leisure 	41.39B
241 	KR 	Kroger Co 	$67.07 	-2.34% 	39.8 	Retail 	40.44B
242 	EME 	Emcor Group Inc 	$849.20 	-0.46% 	30.2 	Construction 	40.37B
243 	AIG 	American International Group 	$78.62 	+0.76% 	12.7 	Insurance 	40.27B
244 	PYPL 	Paypal Holdings Inc 	$44.30 	-0.17% 	7.8 	Financial Services 	39.66B
245 	KDP 	Keurig Dr Pepper Inc 	$28.78 	+0.31% 	21.6 	Beverages 	39.59B
246 	BDX 	Becton Dickinson And Co 	$146.25 	-0.48% 	34.6 	Health Care 	39.33B
247 	LYV 	Live Nation Entertainment In 	$165.98 	+0.94% 	467.3 	Media 	39.10B
248 	ED 	Consolidated Edison Inc 	$107.40 	+1.03% 	19.3 	Utilities 	38.96B
249 	CBRE 	Cbre Group Inc - A 	$131.04 	-0.06% 	29.6 	Real Estate 	38.78B
250 	ADM 	Archer-Daniels-Midland Co 	$77.12 	-0.55% 	35.6 	Food Products 	38.46B
251 	HSY 	Hershey Co/The 	$190.39 	-0.24% 	35.1 	Food Products 	38.42B
252 	DHI 	Dr Horton Inc 	$144.14 	+1.68% 	12.1 	Consumer products 	38.39B
253 	PEG 	Public Service Enterprise Gp 	$78.48 	+0.54% 	16.9 	Utilities 	38.14B
254 	HIG 	Hartford Insurance Group Inc 	$136.02 	-0.49% 	9.1 	Insurance 	36.99B
255 	TKO 	Tko Group Holdings Inc 	$191.63 	-1.36% 	160.9 	Media 	36.79B
256 	WEC 	Wec Energy Group Inc 	$112.11 	+1.32% 	22.2 	Utilities 	36.36B
257 	HUM 	Humana Inc 	$303.68 	-0.14% 	31.9 	Health Care 	36.08B
258 	JBL 	Jabil Inc 	$356.41 	+3.26% 	44.5 	Electrical Equipment 	36.02B
259 	PCG 	P G & E Corp 	$16.44 	+0.80% 	12.1 	Utilities 	35.75B
260 	VMC 	Vulcan Materials Co 	$262.08 	-0.45% 	32.1 	Construction 	35.69B
261 	EQT 	Eqt Corp 	$57.74 	-0.16% 	10.8 	Energy 	35.35B
262 	PRU 	Prudential Financial Inc 	$104.24 	+0.99% 	10.1 	Insurance 	35.08B
263 	SYY 	Sysco Corp 	$77.00 	+2.04% 	19.4 	Retail 	34.83B
264 	HAL 	Halliburton Co 	$41.96 	-0.80% 	22.4 	Energy 	34.44B
265 	CCL 	Carnival Corp 	$26.18 	+0.58% 	11.1 	Hotels, Restaurants & Leisure 	34.38B
266 	Q 	Qnity Electronics Inc 	$152.76 	-0.18% 	68.2 	Semiconductors 	34.36B
267 	MLM 	Martin Marietta Materials 	$537.97 	-0.74% 	13.4 	Construction 	34.02B
268 	LVS 	Las Vegas Sands Corp 	$49.45 	-0.34% 	18.2 	Hotels, Restaurants & Leisure 	33.54B
269 	KVUE 	Kenvue Inc 	$17.46 	+0.81% 	20.4 	Consumer products 	33.00B
270 	STLD 	Steel Dynamics Inc 	$231.84 	+1.55% 	24.0 	Metals & Mining 	32.91B
271 	ACGL 	Arch Capital Group Ltd 	$96.13 	-0.73% 	6.7 	Insurance 	32.84B
272 	WAT 	Waters Corp 	$340.99 	-0.10% 	72.8 	Life Sciences Tools & Services 	32.71B
273 	ROP 	Roper Technologies Inc 	$324.08 	+0.30% 	19.1 	Technology 	32.70B
274 	PAYX 	Paychex Inc 	$94.25 	-0.71% 	19.8 	Professional Services 	32.39B
275 	KMB 	Kimberly-Clark Corp 	$98.73 	+1.21% 	15.1 	Consumer products 	31.96B
276 	CPRT 	Copart Inc 	$34.40 	+4.12% 	20.3 	Commercial Services & Supplies 	31.68B
277 	A 	Agilent Technologies Inc 	$114.79 	+0.89% 	24.6 	Life Sciences Tools & Services 	31.68B
278 	ZTS 	Zoetis Inc 	$80.07 	+0.45% 	12.0 	Pharmaceuticals 	31.64B
279 	AXON 	Axon Enterprise Inc 	$389.84 	-2.16% 	151.9 	Aerospace & Defense 	31.29B
280 	HBAN 	Huntington Bancshares Inc 	$15.85 	+0.19% 	14.2 	Banking 	31.24B
281 	WDAY 	Workday Inc-Class A 	$121.85 	-3.76% 	24.8 	Technology 	31.21B
282 	NTRS 	Northern Trust Corp 	$167.11 	+0.69% 	16.3 	Financial Services 	30.42B
283 	RJF 	Raymond James Financial Inc 	$150.42 	-1.09% 	14.1 	Financial Services 	30.18B
284 	UAL 	United Airlines Holdings Inc 	$99.64 	+1.65% 	8.2 	Airlines 	30.14B
285 	MTB 	M & T Bank Corp 	$212.33 	+0.91% 	10.2 	Banking 	29.87B
286 	DTE 	Dte Energy Company 	$143.75 	+0.69% 	23.6 	Utilities 	29.77B
287 	ATO 	Atmos Energy Corp 	$177.46 	+0.83% 	22.0 	Utilities 	29.61B
288 	AEE 	Ameren Corporation 	$109.84 	+1.06% 	19.4 	Utilities 	29.56B
289 	RMD 	Resmed Inc 	$208.98 	-0.42% 	19.4 	Health Care 	29.45B
290 	FISV 	Fiserv Inc 	$55.82 	-1.05% 	9.1 	Financial Services 	29.03B
291 	EL 	Estee Lauder Companies-Cl A 	$78.91 	+0.91% 	— 	Consumer products 	28.89B
292 	TDY 	Teledyne Technologies Inc 	$607.12 	-1.15% 	30.8 	Electrical Equipment 	28.77B
293 	CNC 	Centene Corp 	$57.77 	-0.88% 	— 	Health Care 	28.71B
294 	BIIB 	Biogen Inc 	$189.47 	+0.89% 	20.9 	Biotechnology 	28.63B
295 	GEHC 	Ge Healthcare Technology 	$64.33 	+0.11% 	14.9 	Health Care 	28.51B
296 	IQV 	Iqvia Holdings Inc 	$168.02 	-2.03% 	20.6 	Life Sciences Tools & Services 	28.46B
297 	DOV 	Dover Corp 	$207.77 	-1.52% 	25.7 	Machinery 	28.29B
298 	DOW 	Dow Inc 	$35.91 	-0.99% 	— 	Chemicals 	27.93B
299 	IR 	Ingersoll-Rand Inc 	$70.28 	-0.13% 	46.9 	Machinery 	27.53B
300 	NRG 	Nrg Energy Inc 	$136.92 	+2.19% 	114.9 	Utilities 	27.47B
301 	ARES 	Ares Management Corp - A 	$123.99 	+1.54% 	52.0 	Financial Services 	27.40B
302 	OTIS 	Otis Worldwide Corp 	$71.63 	+0.51% 	18.4 	Machinery 	27.25B
303 	KHC 	Kraft Heinz Co/The 	$23.54 	+0.04% 	— 	Food Products 	27.18B
304 	CNP 	Centerpoint Energy Inc 	$42.47 	+0.54% 	25.3 	Utilities 	27.06B
305 	TPL 	Texas Pacific Land Corp 	$396.98 	-1.38% 	53.1 	Energy 	26.76B
306 	VRSN 	Verisign Inc 	$305.93 	+0.97% 	31.7 	Technology 	26.66B
307 	EIX 	Edison International 	$70.32 	+0.83% 	7.1 	Utilities 	26.65B
308 	EXPE 	Expedia Group Inc 	$218.12 	+0.24% 	17.9 	Hotels, Restaurants & Leisure 	26.58B
309 	PPL 	Ppl Corp 	$36.17 	+2.06% 	22.5 	Utilities 	26.58B
310 	TPR 	Tapestry Inc 	$139.11 	+2.45% 	39.4 	Textiles, Apparel & Luxury Goods 	26.14B
311 	FOX 	Fox Corp - Class B 	$57.63 	+0.44% 	13.8 	Media 	26.09B
312 	FOXA 	Fox Corp - Class A 	$64.26 	+0.20% 	13.8 	Media 	26.09B
313 	XYL 	Xylem Inc 	$108.70 	+0.44% 	26.5 	Machinery 	26.01B
314 	ROL 	Rollins Inc 	$53.02 	-0.47% 	48.7 	Commercial Services & Supplies 	25.77B
315 	CINF 	Cincinnati Financial Corp 	$168.37 	-0.09% 	9.3 	Insurance 	25.63B
316 	CFG 	Citizens Financial Group 	$62.78 	-0.08% 	13.0 	Banking 	25.61B
317 	HUBB 	Hubbell Inc 	$460.98 	-0.51% 	28.2 	Electrical Equipment 	25.56B
318 	FE 	Firstenergy Corp 	$45.50 	+0.13% 	24.0 	Utilities 	25.52B
319 	FICO 	Fair Isaac Corp 	$1,228.10 	-0.17% 	33.4 	Technology 	25.33B
320 	ES 	Eversource Energy 	$69.63 	+0.84% 	14.4 	Utilities 	25.20B
321 	CTRA 	Coterra Energy Inc 	$32.56 	-8.62% 	14.4 	Energy 	24.72B
322 	AWK 	American Water Works Co Inc 	$123.88 	+1.24% 	22.4 	Utilities 	24.63B
323 	WRB 	Wr Berkley Corp 	$67.47 	-1.13% 	13.1 	Insurance 	24.58B
324 	STZ 	Constellation Brands Inc-A 	$150.83 	-0.23% 	14.4 	Beverages 	24.22B
325 	FSLR 	First Solar Inc 	$248.88 	+4.63% 	14.5 	Semiconductors 	24.15B
326 	JBHT 	Hunt (Jb) Transprt Svcs Inc 	$259.23 	-1.39% 	38.6 	Road & Rail 	24.03B
327 	SYF 	Synchrony Financial 	$72.00 	-0.07% 	6.7 	Financial Services 	24.01B
328 	BG 	Bunge Global Sa 	$120.46 	+0.43% 	34.7 	Food Products 	23.68B
329 	LYB 	Lyondellbasell Indu-Cl A 	$70.08 	-1.71% 	— 	Chemicals 	23.65B
330 	DXCM 	Dexcom Inc 	$71.90 	+0.64% 	25.3 	Health Care 	23.51B
331 	WTW 	Willis Towers Watson Plc 	$258.23 	+1.65% 	14.0 	Insurance 	23.39B
332 	NTAP 	Netapp Inc 	$123.95 	+4.18% 	19.3 	Technology 	23.38B
333 	EXE 	Expand Energy Corp 	$97.59 	-1.27% 	7.2 	Energy 	23.13B
334 	PPG 	Ppg Industries Inc 	$106.63 	+2.15% 	14.6 	Chemicals 	23.07B
335 	DG 	Dollar General Corp 	$105.11 	+0.48% 	15.3 	Retail 	23.06B
336 	TSN 	Tyson Foods Inc-Cl A 	$66.47 	-0.08% 	50.7 	Food Products 	22.95B
337 	RF 	Regions Financial Corp 	$27.71 	+0.65% 	10.2 	Banking 	22.66B
338 	KEY 	Keycorp 	$21.49 	+0.37% 	11.6 	Banking 	22.50B
339 	DRI 	Darden Restaurants Inc 	$197.07 	-0.10% 	20.2 	Hotels, Restaurants & Leisure 	22.32B
340 	CMS 	Cms Energy Corp 	$73.64 	+0.95% 	20.1 	Utilities 	22.25B
341 	CTSH 	Cognizant Tech Solutions-A 	$52.32 	+1.99% 	10.0 	Technology 	22.24B
342 	CHD 	Church & Dwight Co Inc 	$95.64 	-0.50% 	30.3 	Consumer products 	22.22B
343 	NI 	Nisource Inc 	$47.71 	+1.47% 	23.1 	Utilities 	22.17B
344 	FIS 	Fidelity National Info Serv 	$43.62 	+2.18% 	8.2 	Financial Services 	22.00B
345 	AKAM 	Akamai Technologies Inc 	$146.24 	+1.87% 	50.5 	Technology 	21.96B
346 	TROW 	T Rowe Price Group Inc 	$101.95 	+0.12% 	10.4 	Financial Services 	21.87B
347 	L 	Loews Corp 	$109.18 	+0.37% 	13.3 	Insurance 	21.76B
348 	ULTA 	Ulta Beauty Inc 	$504.05 	+2.22% 	18.9 	Retail 	21.75B
349 	PFG 	Principal Financial Group 	$103.92 	+1.08% 	13.9 	Insurance 	21.73B
350 	CPAY 	Corpay Inc 	$347.46 	-0.86% 	18.3 	Financial Services 	21.52B
351 	ALB 	Albemarle Corp 	$169.90 	-0.18% 	— 	Chemicals 	21.39B
352 	WST 	West Pharmaceutical Services 	$316.13 	+3.48% 	39.1 	Life Sciences Tools & Services 	21.21B
353 	MTD 	Mettler-Toledo International 	$1,090.45 	+0.72% 	24.1 	Life Sciences Tools & Services 	21.12B
354 	PHM 	Pultegroup Inc 	$116.30 	+0.03% 	10.3 	Consumer products 	20.98B
355 	VLTO 	Veralto Corp 	$85.96 	-0.27% 	21.6 	Commercial Services & Supplies 	20.94B
356 	STE 	Steris Plc 	$219.67 	+1.71% 	29.6 	Health Care 	20.93B
357 	SW 	Smurfit Westrock Plc 	$37.74 	+1.64% 	55.1 	Packaging 	20.92B
358 	LH 	Labcorp Holdings Inc 	$255.75 	-0.65% 	22.1 	Health Care 	20.77B
359 	DGX 	Quest Diagnostics Inc 	$193.82 	+0.04% 	20.2 	Health Care 	20.68B
360 	VRSK 	Verisk Analytics Inc 	$171.60 	+0.55% 	22.6 	Professional Services 	20.55B
361 	OMC 	Omnicom Group 	$73.77 	+2.63% 	324.8 	Media 	20.46B
362 	WSM 	Williams-Sonoma Inc 	$191.94 	+6.49% 	18.8 	Retail 	20.45B
363 	LEN 	Lennar Corp-A 	$88.83 	+1.74% 	11.4 	Consumer products 	20.38B
364 	FFIV 	F5 Inc 	$383.70 	+0.33% 	28.7 	Communications 	20.32B
365 	EXPD 	Expeditors Intl Wash Inc 	$157.19 	-0.78% 	24.2 	Logistics & Transportation 	20.26B
366 	DD 	Dupont De Nemours Inc 	$47.15 	-0.21% 	— 	Chemicals 	20.21B
367 	VTRS 	Viatris Inc 	$16.46 	-0.78% 	— 	Pharmaceuticals 	20.10B
368 	RL 	Ralph Lauren Corp 	$374.90 	+13.87% 	21.6 	Textiles, Apparel & Luxury Goods 	19.83B
369 	MRNA 	Moderna Inc 	$47.26 	-1.79% 	— 	Biotechnology 	19.46B
370 	CHTR 	Charter Communications Inc-A 	$148.90 	+2.97% 	3.9 	Media 	19.39B
371 	CHRW 	C.H. Robinson Worldwide Inc 	$178.13 	-1.39% 	33.0 	Logistics & Transportation 	19.35B
372 	PKG 	Packaging Corp Of America 	$213.76 	+0.26% 	26.0 	Packaging 	19.28B
373 	HPQ 	Hp Inc 	$21.90 	+3.94% 	7.6 	Technology 	19.13B
374 	BRO 	Brown & Brown Inc 	$58.52 	+1.90% 	16.6 	Insurance 	19.08B
375 	CF 	Cf Industries Holdings Inc 	$121.69 	-1.31% 	10.9 	Chemicals 	19.07B
376 	LUV 	Southwest Airlines Co 	$40.78 	+2.72% 	23.2 	Airlines 	18.93B
377 	INCY 	Incyte Corp 	$97.41 	+0.34% 	13.2 	Biotechnology 	18.92B
378 	SNA 	Snap-On Inc 	$362.31 	-0.28% 	18.2 	Machinery 	18.80B
379 	EFX 	Equifax Inc 	$163.10 	-1.07% 	26.8 	Professional Services 	18.73B
380 	IFF 	Intl Flavors & Fragrances 	$75.25 	+1.10% 	21.9 	Chemicals 	18.69B
381 	SMCI 	Super Micro Computer Inc 	$33.46 	+0.00% 	15.0 	Technology 	18.67B
382 	EVRG 	Evergy Inc 	$83.65 	+0.59% 	21.1 	Utilities 	18.60B
383 	GPN 	Global Payments Inc 	$72.59 	+2.56% 	— 	Financial Services 	18.49B
384 	LNT 	Alliant Energy Corp 	$73.28 	+1.08% 	22.3 	Utilities 	18.31B
385 	FTV 	Fortive Corp 	$59.02 	-0.02% 	33.1 	Machinery 	17.98B
386 	AMCR 	Amcor Plc 	$38.50 	+1.08% 	26.3 	Packaging 	17.84B
387 	GIS 	General Mills Inc 	$33.47 	-0.45% 	7.9 	Food Products 	17.58B
388 	DLTR 	Dollar Tree Inc 	$95.71 	+2.39% 	13.6 	Retail 	17.39B
389 	LII 	Lennox International Inc 	$480.51 	-2.60% 	21.5 	Building 	17.34B
390 	HOLX 	Hologic Inc 	$76.01 	+0.48% 	31.2 	Health Care 	16.97B
391 	BR 	Broadridge Financial Solutio 	$150.02 	+0.55% 	15.3 	Professional Services 	16.87B
392 	BEN 	Franklin Resources Inc 	$30.86 	-1.09% 	22.4 	Financial Services 	16.47B
393 	PTC 	Ptc Inc 	$145.84 	-1.43% 	13.0 	Technology 	16.25B
394 	IP 	International Paper Co 	$31.50 	+2.01% 	— 	Packaging 	16.16B
395 	ZBH 	Zimmer Biomet Holdings Inc 	$85.31 	-0.08% 	21.0 	Health Care 	15.99B
396 	TSCO 	Tractor Supply Company 	$31.67 	-0.06% 	14.8 	Retail 	15.94B
397 	LDOS 	Leidos Holdings Inc 	$123.04 	-1.09% 	15.6 	Professional Services 	15.91B
398 	TXT 	Textron Inc 	$90.24 	+0.80% 	16.9 	Aerospace & Defense 	15.77B
399 	GNRC 	Generac Holdings Inc 	$247.79 	+1.06% 	82.3 	Electrical Equipment 	15.55B
400 	NDSN 	Nordson Corp 	$286.77 	+3.83% 	29.4 	Machinery 	15.40B
401 	IEX 	Idex Corp 	$205.61 	-1.24% 	30.3 	Machinery 	15.40B
402 	NWS 	News Corp - Class B 	$30.08 	+1.28% 	13.5 	Media 	15.29B
403 	NWSA 	News Corp - Class A 	$26.26 	+1.90% 	13.5 	Media 	15.29B
404 	NVR 	Nvr Inc 	$6,047.87 	+0.96% 	12.1 	Consumer products 	14.95B
405 	BALL 	Ball Corp 	$56.35 	-0.81% 	15.8 	Packaging 	14.86B
406 	LULU 	Lululemon Athletica Inc 	$126.76 	+1.25% 	9.2 	Textiles, Apparel & Luxury Goods 	14.45B
407 	GEN 	Gen Digital Inc 	$24.85 	-0.60% 	14.6 	Technology 	14.20B
408 	EG 	Everest Group Ltd 	$356.45 	-0.55% 	6.8 	Insurance 	13.84B
409 	HAS 	Hasbro Inc 	$90.08 	+1.67% 	— 	Leisure Products 	13.45B
410 	MAS 	Masco Corp 	$67.15 	+0.70% 	16.0 	Building 	13.38B
411 	DECK 	Deckers Outdoor Corp 	$102.62 	+4.46% 	12.8 	Textiles, Apparel & Luxury Goods 	13.35B
412 	CSGP 	Costar Group Inc 	$33.93 	-0.24% 	535.6 	Real Estate 	13.28B
413 	HII 	Huntington Ingalls Industrie 	$317.55 	-1.36% 	22.0 	Aerospace & Defense 	13.28B
414 	APA 	Apa Corp 	$38.34 	-2.49% 	8.6 	Energy 	13.12B
415 	CDW 	Cdw Corp/De 	$106.88 	+0.63% 	12.1 	Electrical Equipment 	13.05B
416 	J 	Jacobs Solutions Inc 	$114.04 	+0.19% 	34.2 	Professional Services 	13.05B
417 	TYL 	Tyler Technologies Inc 	$308.74 	-2.69% 	40.9 	Technology 	12.92B
418 	SOLV 	Solventum Corp 	$76.75 	+0.81% 	9.0 	Health Care 	12.89B
419 	GPC 	Genuine Parts Co 	$97.62 	+2.79% 	214.2 	Distributors 	12.87B
420 	TRMB 	Trimble Inc 	$55.97 	+0.00% 	24.6 	Technology 	12.87B
421 	DVA 	Davita Inc 	$198.66 	+0.91% 	16.1 	Health Care 	12.54B
422 	AIZ 	Assurant Inc 	$255.70 	-0.21% 	12.5 	Insurance 	12.49B
423 	ZBRA 	Zebra Technologies Corp-Cl A 	$242.26 	-0.50% 	29.8 	Electrical Equipment 	12.48B
424 	MKC 	Mccormick & Co-Non Vtg Shrs 	$46.96 	+0.56% 	7.6 	Food Products 	12.45B
425 	PNW 	Pinnacle West Capital 	$101.84 	-0.09% 	18.4 	Utilities 	12.05B
426 	AVY 	Avery Dennison Corp 	$158.90 	+0.37% 	17.5 	Packaging 	12.04B
427 	GL 	Globe Life Inc 	$156.60 	+1.39% 	10.2 	Insurance 	12.04B
428 	IVZ 	Invesco Ltd 	$26.98 	+0.00% 	— 	Financial Services 	11.94B
429 	PNR 	Pentair Plc 	$74.43 	+0.32% 	17.6 	Machinery 	11.84B
430 	COO 	Cooper Cos Inc/The 	$62.85 	+1.78% 	29.4 	Health Care 	11.82B
431 	BBY 	Best Buy Co Inc 	$61.15 	+0.28% 	11.0 	Retail 	11.79B
432 	GDDY 	Godaddy Inc - Class A 	$91.56 	-0.74% 	13.4 	Technology 	11.69B
433 	SWK 	Stanley Black & Decker Inc 	$75.54 	+0.75% 	31.4 	Machinery 	11.65B
434 	APTV 	Aptiv Plc 	$55.85 	+2.35% 	31.8 	Auto Components 	11.60B
435 	ALGN 	Align Technology Inc 	$163.04 	-0.21% 	26.4 	Health Care 	11.33B
436 	ALLE 	Allegion Plc 	$130.70 	+1.12% 	17.8 	Building 	11.27B
437 	PSKY 	Paramount Skydance Cl B 	$10.28 	+1.48% 	— 	Media 	11.07B
438 	HRL 	Hormel Foods Corp 	$21.08 	+1.54% 	22.5 	Food Products 	11.02B
439 	CLX 	Clorox Company 	$95.17 	+0.97% 	14.5 	Consumer products 	10.97B
440 	SJM 	Jm Smucker Co/The 	$101.91 	+1.42% 	— 	Food Products 	10.67B
441 	RVTY 	Revvity Inc 	$95.38 	+0.61% 	44.0 	Life Sciences Tools & Services 	10.55B
442 	PODD 	Insulet Corp 	$156.89 	+0.19% 	34.6 	Health Care 	10.48B
443 	AES 	Aes Corp 	$14.69 	-0.27% 	7.6 	Utilities 	10.32B
444 	UHS 	Universal Health Services-B 	$162.45 	-1.14% 	6.8 	Health Care 	10.32B
445 	DPZ 	Domino'S Pizza Inc 	$316.47 	+0.16% 	17.2 	Hotels, Restaurants & Leisure 	10.18B
446 	SWKS 	Skyworks Solutions Inc 	$73.54 	-1.09% 	28.0 	Semiconductors 	10.11B
447 	TTD 	Trade Desk Inc/The -Class A 	$21.28 	+1.24% 	23.2 	Media 	10.03B
448 	ERIE 	Erie Indemnity Company-Cl A 	$224.73 	+1.20% 	17.5 	Insurance 	9.98B
449 	WYNN 	Wynn Resorts Ltd 	$98.54 	+0.49% 	26.4 	Hotels, Restaurants & Leisure 	9.90B
450 	MOH 	Molina Healthcare Inc 	$181.26 	-0.54% 	51.6 	Health Care 	9.70B
451 	JKHY 	Jack Henry & Associates Inc 	$139.56 	-0.19% 	18.7 	Financial Services 	9.70B
452 	IT 	Gartner Inc 	$157.22 	-0.78% 	13.0 	Technology 	9.60B
453 	MGM 	Mgm Resorts International 	$37.66 	+3.15% 	51.3 	Hotels, Restaurants & Leisure 	9.36B
454 	BAX 	Baxter International Inc 	$19.03 	+1.39% 	— 	Health Care 	8.94B
455 	MTCH 	Match Group Inc 	$35.66 	-0.92% 	12.5 	Media 	8.29B
456 	HSIC 	Henry Schein Inc 	$73.50 	+0.37% 	20.8 	Health Care 	8.20B
457 	TAP 	Molson Coors Beverage Co - B 	$42.53 	-0.54% 	— 	Beverages 	8.11B
458 	AOS 	Smith (A.O.) Corp 	$57.17 	+0.86% 	14.7 	Building 	7.77B
459 	FDS 	Factset Research Systems Inc 	$225.01 	+0.59% 	13.1 	Financial Services 	7.72B
460 	BLDR 	Builders Firstsource Inc 	$73.86 	+3.69% 	26.4 	Building 	7.69B
461 	CRL 	Charles River Laboratories 	$158.86 	+1.81% 	— 	Life Sciences Tools & Services 	7.47B
462 	NCLH 	Norwegian Cruise Line Holdin 	$16.47 	+2.74% 	12.5 	Hotels, Restaurants & Leisure 	7.13B
463 	MOS 	Mosaic Co/The 	$21.94 	+0.37% 	13.1 	Chemicals 	7.07B
464 	TECH 	Bio-Techne Corp 	$47.37 	+1.43% 	65.0 	Life Sciences Tools & Services 	7.05B
465 	PAYC 	Paycom Software Inc 	$134.35 	-2.63% 	14.0 	Professional Services 	6.56B
466 	CAG 	Conagra Brands Inc 	$13.38 	-2.76% 	— 	Food Products 	6.45B
467 	POOL 	Pool Corp 	$181.69 	-0.08% 	15.8 	Distributors 	6.40B
468 	LW 	Lamb Weston Holdings Inc 	$42.81 	+2.03% 	20.4 	Food Products 	6.12B
469 	CPB 	The Campbell'S Company 	$20.05 	+0.25% 	10.9 	Food Products 	6.01B
470 	EPAM 	Epam Systems Inc 	$103.19 	-1.06% 	12.1 	Technology'''
stx = [line.split('\t')[1].strip() for line in sp500.split('\n')]
stx = sorted([s for s in stx if '.' not in s])
print(stx)

['A', 'AAPL', 'ABBV', 'ABNB', 'ABT', 'ACGL', 'ACN', 'ADBE', 'ADI', 'ADM', 'ADP', 'ADSK', 'AEE', 'AEP', 'AES', 'AFL', 'AIG', 'AIZ', 'AJG', 'AKAM', 'ALB', 'ALGN', 'ALL', 'ALLE', 'AMAT', 'AMCR', 'AMD', 'AME', 'AMGN', 'AMP', 'AMZN', 'ANET', 'AON', 'AOS', 'APA', 'APD', 'APH', 'APO', 'APP', 'APTV', 'ARES', 'ATO', 'AVGO', 'AVY', 'AWK', 'AXON', 'AXP', 'AZO', 'BA', 'BAC', 'BALL', 'BAX', 'BBY', 'BDX', 'BEN', 'BG', 'BIIB', 'BK', 'BKNG', 'BKR', 'BLDR', 'BLK', 'BMY', 'BR', 'BRO', 'BSX', 'BX', 'C', 'CAG', 'CAH', 'CARR', 'CAT', 'CB', 'CBRE', 'CCL', 'CDNS', 'CDW', 'CEG', 'CF', 'CFG', 'CHD', 'CHRW', 'CHTR', 'CI', 'CINF', 'CL', 'CLX', 'CMCSA', 'CME', 'CMG', 'CMI', 'CMS', 'CNC', 'CNP', 'COF', 'COIN', 'COO', 'COP', 'COR', 'COST', 'CPAY', 'CPB', 'CPRT', 'CRH', 'CRL', 'CRM', 'CRWD', 'CSCO', 'CSGP', 'CSX', 'CTAS', 'CTRA', 'CTSH', 'CTVA', 'CVNA', 'CVS', 'CVX', 'D', 'DAL', 'DASH', 'DD', 'DDOG', 'DE', 'DECK', 'DELL', 'DG', 'DGX', 'DHI', 'DHR', 'DIS', 'DLTR', 'DOV', 'DOW', 'DPZ', 'DRI', 'DTE', 'DUK', 'DVA', 'DVN', 'DXCM', 'EA', 'EBAY', 'ECL', 'ED', 'EFX', 'EG', 'EIX', 'EL', 'ELV', 'EME', 'EMR', 'EOG', 'EPAM', 'EQT', 'ERIE', 'ES', 'ETN', 'ETR', 'EVRG', 'EW', 'EXC', 'EXE', 'EXPD', 'EXPE', 'F', 'FANG', 'FAST', 'FCX', 'FDS', 'FDX', 'FE', 'FFIV', 'FICO', 'FIS', 'FISV', 'FITB', 'FIX', 'FOX', 'FOXA', 'FSLR', 'FTNT', 'FTV', 'GD', 'GDDY', 'GE', 'GEHC', 'GEN', 'GEV', 'GILD', 'GIS', 'GL', 'GLW', 'GM', 'GNRC', 'GOOG', 'GOOGL', 'GPC', 'GPN', 'GRMN', 'GS', 'GWW', 'HAL', 'HAS', 'HBAN', 'HCA', 'HD', 'HIG', 'HII', 'HLT', 'HOLX', 'HON', 'HOOD', 'HPE', 'HPQ', 'HRL', 'HSIC', 'HSY', 'HUBB', 'HUM', 'HWM', 'IBKR', 'IBM', 'ICE', 'IDXX', 'IEX', 'IFF', 'INCY', 'INTC', 'INTU', 'IP', 'IQV', 'IR', 'ISRG', 'IT', 'ITW', 'IVZ', 'J', 'JBHT', 'JBL', 'JCI', 'JKHY', 'JNJ', 'JPM', 'KDP', 'KEY', 'KEYS', 'KHC', 'KKR', 'KLAC', 'KMB', 'KMI', 'KO', 'KR', 'KVUE', 'L', 'LDOS', 'LEN', 'LH', 'LHX', 'LII', 'LIN', 'LLY', 'LMT', 'LNT', 'LOW', 'LRCX', 'LULU', 'LUV', 'LVS', 'LW', 'LYB', 'LYV', 'MA', 'MAR', 'MAS', 'MCD', 'MCHP', 'MCK', 'MCO', 'MDLZ', 'MDT', 'MET', 'META', 'MGM', 'MKC', 'MLM', 'MMM', 'MNST', 'MO', 'MOH', 'MOS', 'MPC', 'MPWR', 'MRK', 'MRNA', 'MS', 'MSCI', 'MSFT', 'MSI', 'MTB', 'MTCH', 'MTD', 'MU', 'NCLH', 'NDAQ', 'NDSN', 'NEE', 'NEM', 'NFLX', 'NI', 'NKE', 'NOC', 'NOW', 'NRG', 'NSC', 'NTAP', 'NTRS', 'NUE', 'NVDA', 'NVR', 'NWS', 'NWSA', 'NXPI', 'ODFL', 'OKE', 'OMC', 'ON', 'ORCL', 'ORLY', 'OTIS', 'OXY', 'PANW', 'PAYC', 'PAYX', 'PCAR', 'PCG', 'PEG', 'PEP', 'PFE', 'PFG', 'PG', 'PGR', 'PH', 'PHM', 'PKG', 'PLTR', 'PM', 'PNC', 'PNR', 'PNW', 'PODD', 'POOL', 'PPG', 'PPL', 'PRU', 'PSKY', 'PSX', 'PTC', 'PWR', 'PYPL', 'Q', 'QCOM', 'RCL', 'REGN', 'RF', 'RJF', 'RL', 'RMD', 'ROK', 'ROL', 'ROP', 'ROST', 'RSG', 'RTX', 'RVTY', 'SBUX', 'SCHW', 'SHW', 'SJM', 'SLB', 'SMCI', 'SNA', 'SNDK', 'SNPS', 'SO', 'SOLV', 'SPGI', 'SRE', 'STE', 'STLD', 'STT', 'STX', 'STZ', 'SW', 'SWK', 'SWKS', 'SYF', 'SYK', 'SYY', 'T', 'TAP', 'TDG', 'TDY', 'TECH', 'TEL', 'TER', 'TFC', 'TGT', 'TJX', 'TKO', 'TMO', 'TMUS', 'TPL', 'TPR', 'TRGP', 'TRMB', 'TROW', 'TRV', 'TSCO', 'TSLA', 'TSN', 'TT', 'TTD', 'TTWO', 'TXN', 'TXT', 'TYL', 'UAL', 'UBER', 'UHS', 'ULTA', 'UNH', 'UNP', 'UPS', 'URI', 'USB', 'V', 'VLO', 'VLTO', 'VMC', 'VRSK', 'VRSN', 'VRTX', 'VST', 'VTRS', 'VZ', 'WAB', 'WAT', 'WBD', 'WDAY', 'WDC', 'WEC', 'WFC', 'WM', 'WMB', 'WMT', 'WRB', 'WSM', 'WST', 'WTW', 'WYNN', 'XEL', 'XOM', 'XYL', 'XYZ', 'YUM', 'ZBH', 'ZBRA', 'ZTS']

In [26]:
#rm = ['NVEE', 'TSMC']
#for s in rm:
#    if s in all_stocks:
#        all_stocks.remove(s)
#        print('removed', s)

In [29]:
with open(f'{DATA}/all_symbols.pkl', 'wb') as f:
    pickle.dump(stx, f)

In [1]:
print(str(sorted(['RCL', 'REGN', 'RF', 'RJF', 'RL', 'RMD', 'ROK', 'ROL', 'ROP', 'ROST', 'RSG', 'RTX', 'RVTY', 'SBUX', 'SCHW', 'SHW', 'SJM', 'SLB', 'SMCI', 'SNA', 'SNDK', 'SNPS', 'SO', 'SOLV', 'SPGI', 'SRE', 'STE', 'STLD', 'STT', 'STX', 'STZ', 'SW', 'SWK', 'SWKS', 'SYF', 'SYK', 'SYY', 'T', 'TAP', 'TDG', 'TDY', 'TECH', 'TEL', 'TER', 'TFC', 'TGT', 'TJX', 'TKO', 'TMO', 'TMUS', 'TPL', 'TPR', 'TRGP', 'TRMB', 'TROW', 'TRV', 'TSCO', 'TSLA', 'TSN', 'TT', 'TTD', 'TTWO', 'TXN', 'TXT', 'TYL', 'UAL', 'UBER', 'UHS', 'ULTA', 'UNH', 'UNP', 'UPS', 'URI', 'USB', 'V', 'VLO', 'VLTO', 'VMC', 'VRSK', 'VRSN', 'VRTX', 'VST', 'VTRS', 'VZ', 'WAB', 'WAT', 'WBD', 'WDAY', 'WDC', 'WEC', 'WFC', 'WM', 'WMB', 'WMT', 'WRB', 'WSM', 'WST', 'WTW', 'WYNN', 'XEL', 'XOM', 'XYL', 'XYZ', 'YUM', 'ZBH', 'ZBRA', 'ZTS'] + ["SAIA", "SAIC", "SAN", "SAP", "SBAC", "SBSW", "SBUX", "SCCO", "SERV", "SH\
G", "SLV", "SMCI", "SNPS", "SONY", "SPOT", "SPSC", "SPY", "SRGHY", "SSL", "STE", \
"STLA", "STN", "STRL", "STZ", "SYK", "SYY", "TCEHY", "TCOM", "TDG", "TECH", "TECK\
", "TER", "TJX", "TKLF", "TLK", "TM", "TME", "TMO", "TMUS", "TOST", "TSCO", "TSLA\
", "TSM", "TTAN", "TTC", "TTD", "TYL", "U", "UBSI", "UL", "UNH", "UVV", "V", "VGK\
", "VLTO", "VEEV", "VRTX", "VTRS", "WFC", "WING", "WIT", "WM", "WMT", "WPM", "XPE\
V", "YTRA", "YUMC", "ZBRA", "ZM"])).replace("'", '"'))

["RCL", "REGN", "RF", "RJF", "RL", "RMD", "ROK", "ROL", "ROP", "ROST", "RSG", "RTX", "RVTY", "SAIA", "SAIC", "SAN", "SAP", "SBAC", "SBSW", "SBUX", "SBUX", "SCCO", "SCHW", "SERV", "SHG", "SHW", "SJM", "SLB", "SLV", "SMCI", "SMCI", "SNA", "SNDK", "SNPS", "SNPS", "SO", "SOLV", "SONY", "SPGI", "SPOT", "SPSC", "SPY", "SRE", "SRGHY", "SSL", "STE", "STE", "STLA", "STLD", "STN", "STRL", "STT", "STX", "STZ", "STZ", "SW", "SWK", "SWKS", "SYF", "SYK", "SYK", "SYY", "SYY", "T", "TAP", "TCEHY", "TCOM", "TDG", "TDG", "TDY", "TECH", "TECH", "TECK", "TEL", "TER", "TER", "TFC", "TGT", "TJX", "TJX", "TKLF", "TKO", "TLK", "TM", "TME", "TMO", "TMO", "TMUS", "TMUS", "TOST", "TPL", "TPR", "TRGP", "TRMB", "TROW", "TRV", "TSCO", "TSCO", "TSLA", "TSLA", "TSM", "TSN", "TT", "TTAN", "TTC", "TTD", "TTD", "TTWO", "TXN", "TXT", "TYL", "TYL", "U", "UAL", "UBER", "UBSI", "UHS", "UL", "ULTA", "UNH", "UNH", "UNP", "UPS", "URI", "USB", "UVV", "V", "V", "VEEV", "VGK", "VLO", "VLTO", "VLTO", "VMC", "VRSK", "VRSN", "VRTX", "VRTX", "VST", "VTRS", "VTRS", "VZ", "WAB", "WAT", "WBD", "WDAY", "WDC", "WEC", "WFC", "WFC", "WING", "WIT", "WM", "WM", "WMB", "WMT", "WMT", "WPM", "WRB", "WSM", "WST", "WTW", "WYNN", "XEL", "XOM", "XPEV", "XYL", "XYZ", "YTRA", "YUM", "YUMC", "ZBH", "ZBRA", "ZBRA", "ZM", "ZTS"]